<option value="Ação judicial">Ação judicial</option>
<option value="Adiantamento">Adiantamento</option>
<option value="Adoção de providências">Adoção de providências</option>
<option value="Anti-Corrupção">Anti-Corrupção</option>
<option value="Aposentadoria">Aposentadoria</option>
<option value="Aquisição">Aquisição</option>
<option value="Ascensão de nível">Ascensão de nível</option>
<option value="Auditorias ordinárias">Auditorias ordinárias</option>
<option value="Auditorias especiais">Auditorias especiais</option>
<option value="Balancete">Balancete</option>
<option value="CEIS">CEIS</option>
<option value="Consultas de órgãos internos">Consultas de órgãos internos</option>
<option value="Contrato">Contrato</option>
<option value="Convênio">Convênio</option>
<option value="Correição">Correição</option>
<option value="Designação">Designação</option>
<option value="Despesas Exercícios Anteriores PF">Despesas Exercícios Anteriores PF</option>
<option value="Despesas Exercícios Anteriores PJ">Despesas Exercícios Anteriores PJ</option>
<option value="Diárias">Diárias</option>
<option value="Diversos">Diversos</option>
<option value="Encaminhamento de documentos">Encaminhamento de documentos</option>
<option value="Exercícios anteriores">Exercícios anteriores</option>
<option value="FECOEP">FECOEP</option>
<option value="Indenização por arma de fogo">Indenização por arma de fogo</option>
<option value="Informação">Informação</option>
<option value="Monitoramento">Monitoramento</option>
<option value="Ouvidoria">Ouvidoria</option>
<option value="Pagamento">Pagamento</option>
<option value="Passagem Aérea">Passagem Aérea</option>
<option value="Pedido de informação">Pedido de informação</option>
<option value="Prestação de contas">Prestação de contas</option>
<option value="Portal da Transparência">Portal da Transparência</option>	
<option value="Reclamação">Reclamação</option>	
<option value="Relatório">Relatório</option>	
<option value="Ressarcimento">Ressarcimento</option>	
<option value="Requerimento e retroativo">Requerimento e retroativo</option>	
<option value="SIC">SIC</option>
<option value="Solicitação">Solicitação</option>
<option value="Outros">Outros</option>