ALTER TABLE tb_processos CHANGE DS_PROCESSO ID_ASSUNTO VARCHAR(50) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;

ALTER TABLE tb_processos CHANGE URGENTE NR_URGENCIA TINYINT(4) NOT NULL DEFAULT '0';

UPDATE tb_processos SET ID_ASSUNTO='Ouvidoria' WHERE NM_TIPO='Ouvidoria';

UPDATE tb_processos SET NM_TIPO='Processo Externo' WHERE NM_TIPO='Ouvidoria';

UPDATE tb_processos SET ID_ASSUNTO='LAI' WHERE NM_TIPO='LAI';

UPDATE tb_processos SET NM_TIPO='Processo Externo' WHERE NM_TIPO='LAI';

UPDATE tb_processos SET NM_TIPO='Processo Interno' WHERE NM_TIPO='Processo Administrativo';

UPDATE tb_processos SET NM_TIPO='Processo Externo' WHERE NM_TIPO='Denúncia';

UPDATE tb_processos SET NM_TIPO='Processo Externo' WHERE NM_TIPO='Judiciário';

UPDATE tb_processos SET ID_ASSUNTO='Ouvidoria' WHERE NM_TIPO='Outros' and ID_ASSUNTO='Denúncia';

UPDATE tb_processos SET NM_TIPO='Processo Externo' WHERE ID_ASSUNTO='Ouvidoria';

UPDATE tb_processos SET NM_TIPO='Processo Externo' WHERE ID_ASSUNTO='SIC';

UPDATE tb_processos SET NM_TIPO='Processo Interno' WHERE ID_ASSUNTO='Prestação de contas';

UPDATE tb_processos SET ID_ASSUNTO='Ouvidoria' WHERE ID_ASSUNTO IN ('Denúncia', 'Reclamação');

UPDATE tb_processos SET ID_ASSUNTO='LAI', NM_TIPO='Processo Externo' WHERE ID_ASSUNTO IN ('Informação', 'Pedido de Informação', 'Solicitação', 'Solicitações');

UPDATE tb_processos SET NM_TIPO='Processo Interno' WHERE ID_ASSUNTO='Prestação de Contas';

UPDATE tb_processos SET ID_ASSUNTO='Indenização por arma de fogo ou drogas' WHERE ID_ASSUNTO='Pagamento de indenização por arma de fogo e drogas';

UPDATE tb_processos SET ID_ASSUNTO='Pagamentos' WHERE ID_ASSUNTO='Pagamento';

UPDATE tb_processos SET ID_ASSUNTO='Indenização por arma de fogo ou drogas' WHERE ID_ASSUNTO='Indenização por arma de fogo';

UPDATE tb_processos SET ID_ASSUNTO='' WHERE ID_ASSUNTO='Diversos' or ID_ASSUNTO='Outros';


CREATE TABLE `tb_assuntos_processos` (
  `ID` int(3) NOT NULL,
  `NM_ASSUNTO` varchar(50) NOT NULL,
  `NM_TIPO` varchar(50) NOT NULL,
  `CD_SETOR_RESPONSAVEL` varchar(11) NOT NULL,
  `NR_DIAS_PRAZO` int(3) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=COMPACT;

--
-- Extraindo dados da tabela `tb_assuntos_processos`
--

INSERT INTO `tb_assuntos_processos` (`ID`, `NM_ASSUNTO`, `NM_TIPO`, `CD_SETOR_RESPONSAVEL`, `NR_DIAS_PRAZO`) VALUES
(1, '13º Salário', 'Externo', 'SUP-SUCOF', 90),
(2, 'Abono Permanência', 'Externo', 'SUP-SUCOF', 90),
(3, 'Ação judicial', 'Externo', 'SUP-SUPAD', 0),
(4, 'Adiantamento', 'Interno', 'FIN', 30),
(5, 'Adoção de providências', 'Externo', 'SUP-SUPAD', 0),
(6, 'Anti-Corrupção', 'Externo', 'SUP-SUPAD', 0),
(7, 'Anuênio', 'Externo', 'SUP-SUCOF', 90),
(8, 'Aposentadoria', 'Externo', 'SUP-SUCOF', 90),
(9, 'Apostilamento anuênio', 'Externo', 'SUP-SUCOF', 90),
(10, 'Apostilamento quinquênio', 'Externo', 'SUP-SUCOF', 90),
(11, 'Aquisição', 'Interno', 'FIN', 90),
(12, 'Ascensão de nível', 'Externo', 'SUP-SUPAD', 0),
(13, 'Auditorias ordinárias', 'Externo', 'SUP-SUPAD', 0),
(14, 'Auditorias especiais', 'Externo', 'SUP-SUPAD', 0),
(15, 'Balancete', 'Externo', 'SUP-SUCOF', 90),
(16, 'CEIS', 'Externo', 'SUP-SUCOR', 40),
(17, 'Consultas de órgãos internos', 'Externo', 'SUP-SUPAD', 0),
(18, 'Contrato', 'Externo', 'SUP-SUPAD', 0),
(19, 'Convênio', 'Externo', 'SUP-SUCOF', 90),
(20, 'Correição', 'Externo', 'SUP-SUCOR', 40),
(21, 'Designação', 'Externo', 'SUP-SUPAD', 0),
(22, 'Despesas Exercícios Anteriores PF', 'Externo', 'SUP-SUPAD', 0),
(23, 'Despesas Exercícios Anteriores PJ', 'Externo', 'SUP-SUPAD', 0),
(24, 'Diárias', 'Interno', 'FIN', 30),
(25, 'Encaminhamento de documentos', 'Externo', 'SUP-SUPAD', 0),
(26, 'Execução Orçamentária', 'Externo', 'SUP-SUCOF', 90),
(27, 'Exercícios anteriores', 'Externo', 'SUP-SUPAD', 0),
(28, 'FECOEP', 'Externo', 'SUP-SUCOF', 90),
(29, 'Férias', 'Externo', 'SUP-SUCOF', 90),
(30, 'Hora Extra', 'Externo', 'SUP-SUCOF', 90),
(31, 'Indenização por arma de fogo ou drogas', 'Externo', 'SUP-SUPAD', 0),
(32, 'LAI', 'Externo', 'SUP-SUCOR', 30),
(33, 'Monitoramento', 'Interno', 'SUP-SUPAD', 0),
(34, 'Mudança de Classe', 'Interno', 'SUP-SUCOF', 90),
(35, 'Ouvidoria', 'Externo', 'SUP-SUCOR', 90),
(36, 'Pagamentos', 'Interno', 'FIN', 30),
(37, 'Pagamento de Indenização', 'Interno', 'SUP-SUCOF', 90),
(38, 'Passagem Aérea', 'Interno', 'FIN', 30),
(39, 'Prestação de contas Convênio', 'Interno', 'SUP-SUCOF', 120),
(40, 'Prestação de contas FECOEP', 'Interno', 'SUP-SUCOF', 120),
(41, 'Prestação de Contas Programa Nota Fiscal Cidadã', 'Interno', 'SUP-SUCOF', 120),
(42, 'Progressão por Nova Habilitação', 'Interno', 'SUP-SUCOF', 120),
(43, 'Portal da Transparência', 'Externo', 'SUP-SUCOR', 30),
(44, 'Relatório', 'Externo', 'SUP-SUPAD', 0),
(45, 'Ressarcimento', 'Externo', 'SUP-SUPAD', 0),
(46, 'Requerimento e retroativo', 'Externo', 'SUP-SUPAD', 0),
(47, 'RMA e RMB', 'Externo', 'SUP-SUCOF', 90),
(48, 'SIC', 'Externo', 'SUP-SUCOR', 40),
(49, 'Verba de Alimentação', 'Externo', 'SUP-SUCOF', 90);

--
-- Indexes for dumped tables
--

--
-- Indexes for table `tb_assuntos_processos`
--
ALTER TABLE `tb_assuntos_processos`
  ADD PRIMARY KEY (`ID`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `tb_assuntos_processos`
--
ALTER TABLE `tb_assuntos_processos`
  MODIFY `ID` int(3) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=50;

-- ALTER TABLE `tb_processos` DROP `NM_TIPO`;

ALTER TABLE `tb_processos` CHANGE `NM_STATUS` `NM_STATUS` VARCHAR(25) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;

UPDATE tb_processos p SET ID_ASSUNTO=(SELECT ID FROM tb_assuntos_processos WHERE p.ID_ASSUNTO = NM_ASSUNTO);

ALTER TABLE `tb_processos` CHANGE `ID_ASSUNTO` `ID_ASSUNTO` INT(3) NOT NULL;

ALTER TABLE `tb_processos` DROP `DT_PRAZO`;

ALTER TABLE `tb_processos` CHANGE `DT_PRAZO_FINAL` `DT_PRAZO` DATE NOT NULL;

-- 00000000000000

UPDATE tb_processos SET NM_STATUS='Finalizado pelo gabinete' WHERE NM_SITUACAO_FINAL in ('Finalizado', 'Finalizado com atraso') AND NM_STATUS = 'Ativo' AND CD_PROCESSO in (SELECT hp.CD_PROCESSO FROM `tb_historico_processos` hp LEFT JOIN tb_servidores s ON hp.CD_SERVIDOR = s.CD_SERVIDOR WHERE s.CD_SETOR = 'GAB' and hp.NM_ACAO='Finalização');

UPDATE tb_processos SET NM_STATUS='Finalizado pelo setor' WHERE NM_SITUACAO_FINAL in ('Finalizado', 'Finalizado com atraso') AND NM_STATUS = 'Ativo' AND CD_PROCESSO in (SELECT hp.CD_PROCESSO FROM `tb_historico_processos` hp LEFT JOIN tb_servidores s ON hp.CD_SERVIDOR = s.CD_SERVIDOR WHERE s.CD_SETOR != 'GAB' and hp.NM_ACAO='Finalização');

UPDATE tb_processos SET NM_STATUS='Atrasado' WHERE DT_PRAZO < CURDATE() AND NM_STATUS='Ativo';

UPDATE tb_processos SET NM_STATUS='Em andamento' WHERE DT_PRAZO >= CURDATE() AND NM_STATUS='Ativo' AND NM_SITUACAO_FINAL='Finalização em andamento';

UPDATE tb_processos SET NM_STATUS='Em andamento' WHERE NM_SITUACAO_FINAL='Aberto';

ALTER TABLE `tb_processos` DROP `NM_SITUACAO`;

ALTER TABLE `tb_processos` DROP `NM_SITUACAO_FINAL`;

UPDATE tb_documentos SET NM_ATIVIDADE='Indenização por arma de fogo ou drogas' WHERE NM_ATIVIDADE='Indenização por arma de fogo';

UPDATE tb_documentos SET NM_ATIVIDADE='Indenização por arma de fogo ou drogas' WHERE NM_ATIVIDADE='Pagamento de indenização por arma de fogo e drogas';

UPDATE tb_documentos SET NM_ATIVIDADE='LAI' WHERE NM_ATIVIDADE='Informação';

UPDATE tb_documentos SET NM_ATIVIDADE='LAI' WHERE NM_ATIVIDADE='Pedido de informação';

ALTER TABLE `tb_documentos` ADD `ID_ASSUNTO` INT(3) NOT NULL AFTER `CD_PROCESSO`;

UPDATE tb_documentos d SET ID_ASSUNTO=(SELECT ID_ASSUNTO FROM tb_processos p WHERE d.CD_PROCESSO=p.CD_PROCESSO) WHERE CD_PROCESSO!='';

UPDATE tb_documentos d SET ID_ASSUNTO=(SELECT ID FROM tb_assuntos_processos a WHERE d.NM_ATIVIDADE = a.NM_ASSUNTO ) WHERE CD_PROCESSO='';

ALTER TABLE `tb_documentos` DROP `NM_ATIVIDADE`;

ALTER TABLE `tb_processos` ADD `CD_PROCESSO_APENSADO` VARCHAR(17) NOT NULL AFTER `CD_SERVIDOR_LOCALIZACAO`;

ALTER TABLE `tb_servidores` ADD `NM_FUNCAO` VARCHAR(50) NOT NULL AFTER `NM_CARGO`;

ALTER TABLE `tb_processos` ADD `CD_SERVIDOR_RESPONSAVEL_LIDER` VARCHAR(14) NOT NULL AFTER `CD_SERVIDOR_LOCALIZACAO`;

UPDATE permissao SET URGENCIA_PROCESSO='não';

UPDATE permissao SET URGENCIA_PROCESSO='sim' WHERE CD_SERVIDOR IN (SELECT CD_SERVIDOR from tb_servidores WHERE CD_SETOR='GAB' OR NM_CARGO='Superintendente' or CD_SERVIDOR='000.000.000-00');

ALTER TABLE `permissao` DROP `PRAZO_FINAL_PROCESSO`;

-- 0)))))

#Adicionando permissão de acesso ao GUIA
ALTER TABLE `permissao` ADD `ACESSO_GUIA_TRAMITACAO_PROCESSO` VARCHAR(3) NOT NULL DEFAULT 'não' AFTER `URGENCIA_PROCESSO`;

ALTER TABLE `permissao` ADD `APENSO_PROCESSO` VARCHAR(3) NOT NULL AFTER `ACESSO_GUIA_TRAMITACAO_PROCESSO`;

update permissao set APENSO_PROCESSO='não';

UPDATE permissao SET APENSO_PROCESSO='sim' WHERE CD_SERVIDOR IN (SELECT CD_SERVIDOR from tb_servidores WHERE CD_SETOR='PRO' OR NM_CARGO='Superintendente' or CD_SERVIDOR='000.000.000-00');

UPDATE tb_processos SET NM_STATUS='Atrasado' WHERE DT_PRAZO < CURDATE() AND NM_STATUS='Em andamento';

CREATE TABLE `tb_orgaos` ( `ID` INT(6) NOT NULL AUTO_INCREMENT , `NM_ORGAO` VARCHAR(100) NOT NULL , PRIMARY KEY (`ID`)) ENGINE = InnoDB;

INSERT INTO tb_orgaos (NM_ORGAO) VALUES 
('AGENCIA DE DEFESA E INSPECAO AGROPECUARIA ESTADO DE ALAGOAS'),
('AGENCIA DE FOMENTO DE ALAGOAS'),
('AGENCIA DE MODERNIZACAO DA GESTAO DE PROCESSOS'),
('AGENCIA REGULADORA DE SERVICOS PUBLICOS DO ESTADO DE ALAGOAS'),
('AL PREVIDENCIA'),
('ALAGOAS PREVIDENCIA'),
('COMPANHIA ALAGOANA DE RECUROS HUMANOS E PATRIMONIAIS'),
('CONTROLADORIA GERAL DO ESTADO'),
('CORPO DE BOMBEIROS MILITAR DE ALAGOAS'),
('DEFENSORIA PÚBLICA GERAL DO ESTADO'),
('DEPARTAMENTO DE ESTRADAS DE RODAGEM'),
('DEPARTAMENTO ESTADUAL DE TRANSITO DE ALAGOAS'),
('DIRETORIA DE TEATROS DO ESTADO DE ALAGOAS'),
('FUNDACAO DE AMPARO A PESQUISA DE ALAGOAS'),
('GABINETE DO GOVERNADOR'),
('GABINETE DO VICE GOVERNADOR'),
('GABINETE MILITAR DO ESTADO DE ALAGOAS'),
('INSTITUTO DE ASSISTENCIA A SAUDE DOS SERVIDORES DO ESTADO DE ALAGOAS'),
('INSTITUTO DE DESENVOLVIMENTO RURAL E ABASTECIMENTO DE ALAGOAS'),
('INSTITUTO DE INOVACAO PARA O DESENV RURAL SUSTENTAVEL'),
('INSTITUTO DE METROLOGIA E QUALIDADE DE ALAGOAS'),
('INSTITUTO DE TECNOLOGIA EM INFORMATICA E INF DE ALAGOAS'),
('INSTITUTO DE TERRAS E REFORMA AGRARIA DE ALAGOAS'),
('INSTITUTO DO MEIO AMBIENTE DO ESTADO DE ALAGOAS'),
('INSTITUTO ZUMBI DOS PALMARES'),
('JUNTA COMERCIAL DO ESTADO DE ALAGOAS'),
('MINISTÉRIO PÚBLICO DE CONTAS'),
('PERICIA OFICIAL DO ESTADO DE ALAGOAS'),
('POLICIA CIVIL DO ESTADO DE ALAGOAS'),
('POLICIA MILITAR DE ALAGOAS'),
('PROCURADORIA GERAL DO ESTADO'),
('SEC DE ESTADO DA AGRICULTURA PECUARIA PESCA E AQUICULTURA'),
('SECRETARIA  DE ESTADO DE ARTICULAÇÃO SOCIAL DE ALAGOAS'),
('SECRETARIA DE ESTADO DA ASSISTENCIA E DESENVOLVIMENTO SOCIAL'),
('SECRETARIA DE ESTADO DA CIENCIA DA TECNOLOGIA E DA INOVACAO'),
('SECRETARIA DE ESTADO DA COMUNICACAO'),
('SECRETARIA DE ESTADO DA CULTURA'),
('SECRETARIA DE ESTADO DA EDUCACAO'),
('SECRETARIA DE ESTADO DA FAZENDA'),
('SECRETARIA DE ESTADO DA INFRA ESTRUTURA'),
('SECRETARIA DE ESTADO DA MULHER CIDADANIA DIREITOS HUMANOS'),
('SECRETARIA DE ESTADO DA PESCA E AQUICULTURA  DE ALAGOAS'),
('SECRETARIA DE ESTADO DA SAUDE'),
('SECRETARIA DE ESTADO DA SEGURANCA PUBLICA'),
('SECRETARIA DE ESTADO DE ARTICULAÇÃO POLÍTICA DE ALAGOAS'),
('SECRETARIA DE ESTADO DE PREVENCAO A VIOLENCIA'),
('SECRETARIA DE ESTADO DE RESSOCIALIZACAO E INCLUSAO SOCIAL'),
('SECRETARIA DE ESTADO DE TRANSPORTE E DESENVOLVIMENTO URBANO'),
('SECRETARIA DE ESTADO DO DESENVOLVIMENTO ECONOMICO E TURISMO'),
('SECRETARIA DE ESTADO DO ESPORTE LAZER E JUVENTUDE'),
('SECRETARIA DE ESTADO DO MEIO AMBIENTE E RECURSOS HIDRICOS'),
('SECRETARIA DE ESTADO DO PLANEJAMENTO E DO DESENVOLVIMENTO ECONÔMICO DE ALAGOAS'),
('SECRETARIA DE ESTADO DO PLANEJAMENTO GESTAO E PATRIMONIO'),
('SECRETARIA DE ESTADO DO TRABALHO E EMPREGO'),
('SERVICOS DE ENGENHARIA DE ALAGOAS S/A'),
('SUPERINTENDÊNCIA GERAL DE ADMINISTRAÇÃO PENITENCIÁRIA'),
('UNIVERSIDADE ESTADUAL DE ALAGOAS'),
('UNIVERSIDADE ESTADUAL DE CIENCIAS DA SAUDE DE ALAGOAS');

ALTER TABLE `tb_processos` ADD `ID_ORGAO_INTERESSADO` INT(6) NOT NULL AFTER `NM_DETALHES`;

update tb_servidores set nm_funcao='Analisa Processo' where cd_setor in ('SUCOR', 'SUCOF', 'SUPAD');

update tb_servidores set nm_funcao='Assessor Técnico Gabinete' where cd_servidor='082.766.354-40';

update tb_servidores set nm_funcao='Assessor Técnico Setor' where cd_servidor in('058.709.064-23','911.765.904-30','090.752.884-84');

update tb_servidores set nm_funcao='Superintendente' where cd_servidor in('803.589.264-91','030.505.524-09','938.925.605-44');

update tb_servidores set nm_funcao='Protocolo' where cd_servidor in('055.902.374-08','210.090.664-04');

INSERT INTO `tb_setores` (`CD_SETOR`, `NM_SETOR`, `CD_SETOR_SUBORDINADO`) VALUES ('FIN', 'Financeiro', '');

update tb_servidores SET NM_FUNCAO='Superintendente sem assessor' where CD_SERVIDOR IN ('894.568.234-15','870.684.784-68');

update tb_servidores SET CD_SETOR='FIN' where CD_SERVIDOR IN ('894.568.234-15');

ALTER TABLE `permissao` ADD `FINALIZAR_GABINETE_PROCESSO` VARCHAR(3) NOT NULL AFTER `FINALIZAR_PROCESSO`;

update permissao set FINALIZAR_GABINETE_PROCESSO='não';

update permissao set FINALIZAR_GABINETE_PROCESSO='sim' WHERE CD_SERVIDOR IN ('084.688.464-06', '082.766.354-40', '056.411.154-60');

update permissao set FINALIZAR_PROCESSO='não';

update permissao set FINALIZAR_PROCESSO='sim' WHERE CD_SERVIDOR IN ('030.505.524-09', '058.709.064-23', '090.752.884-84', '803.589.264-91', '911.765.904-30', '938.925.605-44');

ALTER TABLE `permissao` ADD `DESFAZER_FINALIZACAO_PROCESSO` VARCHAR(3) NOT NULL AFTER `FINALIZAR_GABINETE_PROCESSO`, ADD `DESFAZER_FINALIZACAO_GABINETE_PROCESSO` VARCHAR(3) NOT NULL AFTER `DESFAZER_FINALIZACAO_PROCESSO`;

update permissao set DESFAZER_FINALIZACAO_GABINETE_PROCESSO='não';

update permissao set DESFAZER_FINALIZACAO_GABINETE_PROCESSO='sim' WHERE CD_SERVIDOR IN ('084.688.464-06', '082.766.354-40', '056.411.154-60');

update permissao set DESFAZER_FINALIZACAO_PROCESSO='não';

update permissao set DESFAZER_FINALIZACAO_PROCESSO='sim' WHERE CD_SERVIDOR IN ('030.505.524-09', '058.709.064-23', '090.752.884-84', '803.589.264-91', '911.765.904-30', '938.925.605-44');

UPDATE permissao SET VISUALIZAR_ATIVIDADE='não',VISUALIZAR_TODAS_ATIVIDADE='não',CADASTRAR_ATIVIDADE='não',AUTORIZAR_COMPRA='não',EFETUAR_COMPRA='não',VISUALIZAR_CHAMADO='sim',VISUALIZAR_TODOS_CHAMADO='não',ABRIR_CHAMADO='sim',ABRIR_TODOS_CHAMADO='não',EXCLUIR_CHAMADO='não',FECHAR_CHAMADO='não',ENCERRAR_CHAMADO='não',NOTA_CHAMADO='sim',VISUALIZAR_RELATORIO_CHAMADO='não',VISUALIZAR_COMUNICACAO='não',CADASTRAR_COMUNICACAO='não',EDITAR_COMUNICACAO='não',EXCLUIR_COMUNICACAO='não',VISUALIZAR_DOCUMENTO='sim',VISUALIZAR_TODOS_SETOR_DOCUMENTO='sim',VISUALIZAR_TODOS_ORGAO_DOCUMENTO='sim',CADASTRAR_DOCUMENTO='não',EDITAR_DOCUMENTO='não',EXCLUIR_DOCUMENTO='não',APROVAR_DOCUMENTO='não',SUGESTAO_DOCUMENTO='não',RESOLVER_DOCUMENTO='não',VISUALIZAR_FINANCEIRO='não',CADASTRAR_RECEITA='não',EXCLUIR_RECEITA='não',CADASTRAR_DESPESA='não',EXCLUIR_DESPESA='não',AUTORIZAR_EMPENHO='não',EMPENHAR_DESPESA='não',AUTORIZAR_PAGAMENTO='não',PAGAR_DESPESA='não',VISUALIZAR_INDICE_PRODUTIVIDADE='não',VISUALIZAR_TODOS_SETOR_INDICE_PRODUTIVIDADE='não',VISUALIZAR_TODOS_ORGAO_INDICE_PRODUTIVIDADE='não',AVALIAR_ASSIDUIDADE='não',NOTA_EXTRA_INDICE_PRODUTIVIDADE='não',SER_AVALIADO_INDICE_PRODUTIVIDADE='não',VISUALIZAR_PROCESSO='sim',VISUALIZAR_TODOS_SETOR_PROCESSO='sim',VISUALIZAR_TODOS_ORGAO_PROCESSO='sim',VISUALIZAR_ARQUIVADOS_PROCESSO='sim',VISUALIZAR_SAIRAM_PROCESSO='sim',ABRIR_PROCESSO='sim',EDITAR_PROCESSO='sim',EXCLUIR_PROCESSO='não',DESPACHO_PROCESSO='não',PARECER_PROCESSO='não',CONCLUIR_PROCESSO='não',FINALIZAR_PROCESSO='não',FINALIZAR_GABINETE_PROCESSO='não',DESFAZER_FINALIZACAO_PROCESSO='não',DESFAZER_FINALIZACAO_GABINETE_PROCESSO='não',ARQUIVAR_PROCESSO='não',DESARQUIVAR_PROCESSO='não',SAIDA_PROCESSO='sim',VOLTAR_PROCESSO='sim',DEFINIR_RESPONSAVEIS_PROCESSO='não',SER_RESPONSAVEL_PROCESSO='não',DESTINO_PROCESSO='sim',PRAZO_PROCESSO='não',URGENCIA_PROCESSO='não',ACESSO_GUIA_TRAMITACAO_PROCESSO='sim',APENSO_PROCESSO='sim',VISUALIZAR_SERVIDORES='não',CADASTRAR_SERVIDORES='não',EDITAR_SERVIDORES='não',EXCLUIR_SERVIDORES='não',VISUALIZAR_SETOR_RELATORIO='não',VISUALIZAR_ORGAO_RELATORIO='não',VISUALIZAR_ODP='não',FAZER_OPERACOES_OUTROS_SETOR='sim',FAZER_OPERACOES_OUTROS_ORGAO='não' WHERE CD_SERVIDOR IN (SELECT CD_SERVIDOR FROM tb_servidores WHERE NM_FUNCAO='Protocolo');

UPDATE permissao SET VISUALIZAR_ATIVIDADE='não',VISUALIZAR_TODAS_ATIVIDADE='não',CADASTRAR_ATIVIDADE='não',AUTORIZAR_COMPRA='sim',EFETUAR_COMPRA='não',VISUALIZAR_CHAMADO='sim',VISUALIZAR_TODOS_CHAMADO='não',ABRIR_CHAMADO='sim',ABRIR_TODOS_CHAMADO='não',EXCLUIR_CHAMADO='não',FECHAR_CHAMADO='não',ENCERRAR_CHAMADO='não',NOTA_CHAMADO='sim',VISUALIZAR_RELATORIO_CHAMADO='não',VISUALIZAR_COMUNICACAO='não',CADASTRAR_COMUNICACAO='não',EDITAR_COMUNICACAO='não',EXCLUIR_COMUNICACAO='não',VISUALIZAR_DOCUMENTO='sim',VISUALIZAR_TODOS_SETOR_DOCUMENTO='sim',VISUALIZAR_TODOS_ORGAO_DOCUMENTO='sim',CADASTRAR_DOCUMENTO='sim',EDITAR_DOCUMENTO='sim',EXCLUIR_DOCUMENTO='não',APROVAR_DOCUMENTO='não',SUGESTAO_DOCUMENTO='não',RESOLVER_DOCUMENTO='sim',VISUALIZAR_FINANCEIRO='sim',CADASTRAR_RECEITA='não',EXCLUIR_RECEITA='não',CADASTRAR_DESPESA='não',EXCLUIR_DESPESA='não',AUTORIZAR_EMPENHO='sim',EMPENHAR_DESPESA='não',AUTORIZAR_PAGAMENTO='sim',PAGAR_DESPESA='não',VISUALIZAR_INDICE_PRODUTIVIDADE='não',VISUALIZAR_TODOS_SETOR_INDICE_PRODUTIVIDADE='não',VISUALIZAR_TODOS_ORGAO_INDICE_PRODUTIVIDADE='não',AVALIAR_ASSIDUIDADE='não',NOTA_EXTRA_INDICE_PRODUTIVIDADE='não',SER_AVALIADO_INDICE_PRODUTIVIDADE='não',VISUALIZAR_PROCESSO='sim',VISUALIZAR_TODOS_SETOR_PROCESSO='sim',VISUALIZAR_TODOS_ORGAO_PROCESSO='sim',VISUALIZAR_ARQUIVADOS_PROCESSO='sim',VISUALIZAR_SAIRAM_PROCESSO='sim',ABRIR_PROCESSO='não',EDITAR_PROCESSO='sim',EXCLUIR_PROCESSO='não',DESPACHO_PROCESSO='sim',PARECER_PROCESSO='não',CONCLUIR_PROCESSO='não',FINALIZAR_PROCESSO='não',FINALIZAR_GABINETE_PROCESSO='sim',DESFAZER_FINALIZACAO_PROCESSO='não',DESFAZER_FINALIZACAO_GABINETE_PROCESSO='sim',ARQUIVAR_PROCESSO='sim',DESARQUIVAR_PROCESSO='sim',SAIDA_PROCESSO='não',VOLTAR_PROCESSO='não',DEFINIR_RESPONSAVEIS_PROCESSO='não',SER_RESPONSAVEL_PROCESSO='não',DESTINO_PROCESSO='sim',PRAZO_PROCESSO='sim',URGENCIA_PROCESSO='sim',ACESSO_GUIA_TRAMITACAO_PROCESSO='sim',APENSO_PROCESSO='sim',VISUALIZAR_SERVIDORES='não',CADASTRAR_SERVIDORES='não',EDITAR_SERVIDORES='não',EXCLUIR_SERVIDORES='não',VISUALIZAR_SETOR_RELATORIO='não',VISUALIZAR_ORGAO_RELATORIO='não',VISUALIZAR_ODP='não',FAZER_OPERACOES_OUTROS_SETOR='sim',FAZER_OPERACOES_OUTROS_ORGAO='não' WHERE CD_SERVIDOR IN (SELECT CD_SERVIDOR FROM tb_servidores WHERE NM_FUNCAO='Assessor Técnico Gabinete' or CD_SETOR='GAB');

UPDATE permissao SET VISUALIZAR_ATIVIDADE='não',VISUALIZAR_TODAS_ATIVIDADE='não',CADASTRAR_ATIVIDADE='não',AUTORIZAR_COMPRA='não',EFETUAR_COMPRA='não',VISUALIZAR_CHAMADO='sim',VISUALIZAR_TODOS_CHAMADO='não',ABRIR_CHAMADO='sim',ABRIR_TODOS_CHAMADO='não',EXCLUIR_CHAMADO='não',FECHAR_CHAMADO='não',ENCERRAR_CHAMADO='não',NOTA_CHAMADO='sim',VISUALIZAR_RELATORIO_CHAMADO='não',VISUALIZAR_COMUNICACAO='não',CADASTRAR_COMUNICACAO='não',EDITAR_COMUNICACAO='não',EXCLUIR_COMUNICACAO='não',VISUALIZAR_DOCUMENTO='sim',VISUALIZAR_TODOS_SETOR_DOCUMENTO='sim',VISUALIZAR_TODOS_ORGAO_DOCUMENTO='sim',CADASTRAR_DOCUMENTO='sim',EDITAR_DOCUMENTO='sim',EXCLUIR_DOCUMENTO='não',APROVAR_DOCUMENTO='não',SUGESTAO_DOCUMENTO='não',RESOLVER_DOCUMENTO='sim',VISUALIZAR_FINANCEIRO='não',CADASTRAR_RECEITA='não',EXCLUIR_RECEITA='não',CADASTRAR_DESPESA='não',EXCLUIR_DESPESA='não',AUTORIZAR_EMPENHO='não',EMPENHAR_DESPESA='não',AUTORIZAR_PAGAMENTO='não',PAGAR_DESPESA='não',VISUALIZAR_INDICE_PRODUTIVIDADE='não',VISUALIZAR_TODOS_SETOR_INDICE_PRODUTIVIDADE='não',VISUALIZAR_TODOS_ORGAO_INDICE_PRODUTIVIDADE='não',AVALIAR_ASSIDUIDADE='não',NOTA_EXTRA_INDICE_PRODUTIVIDADE='não',SER_AVALIADO_INDICE_PRODUTIVIDADE='não',VISUALIZAR_PROCESSO='sim',VISUALIZAR_TODOS_SETOR_PROCESSO='sim',VISUALIZAR_TODOS_ORGAO_PROCESSO='sim',VISUALIZAR_ARQUIVADOS_PROCESSO='sim',VISUALIZAR_SAIRAM_PROCESSO='sim',ABRIR_PROCESSO='não',EDITAR_PROCESSO='sim',EXCLUIR_PROCESSO='não',DESPACHO_PROCESSO='sim',PARECER_PROCESSO='não',CONCLUIR_PROCESSO='não',FINALIZAR_PROCESSO='sim',FINALIZAR_GABINETE_PROCESSO='não',DESFAZER_FINALIZACAO_PROCESSO='sim',DESFAZER_FINALIZACAO_GABINETE_PROCESSO='não',ARQUIVAR_PROCESSO='sim',DESARQUIVAR_PROCESSO='sim',SAIDA_PROCESSO='não',VOLTAR_PROCESSO='não',DEFINIR_RESPONSAVEIS_PROCESSO='sim',SER_RESPONSAVEL_PROCESSO='sim',DESTINO_PROCESSO='sim',PRAZO_PROCESSO='sim',URGENCIA_PROCESSO='sim',ACESSO_GUIA_TRAMITACAO_PROCESSO='sim',APENSO_PROCESSO='sim',VISUALIZAR_SERVIDORES='não',CADASTRAR_SERVIDORES='não',EDITAR_SERVIDORES='não',EXCLUIR_SERVIDORES='não',VISUALIZAR_SETOR_RELATORIO='não',VISUALIZAR_ORGAO_RELATORIO='não',VISUALIZAR_ODP='não',FAZER_OPERACOES_OUTROS_SETOR='sim',FAZER_OPERACOES_OUTROS_ORGAO='não' WHERE CD_SERVIDOR IN (SELECT CD_SERVIDOR FROM tb_servidores WHERE NM_FUNCAO='Assessor Técnico Setor');

UPDATE permissao SET VISUALIZAR_ATIVIDADE='sim',VISUALIZAR_TODAS_ATIVIDADE='não',CADASTRAR_ATIVIDADE='não',AUTORIZAR_COMPRA='não',EFETUAR_COMPRA='não',VISUALIZAR_CHAMADO='sim',VISUALIZAR_TODOS_CHAMADO='não',ABRIR_CHAMADO='sim',ABRIR_TODOS_CHAMADO='não',EXCLUIR_CHAMADO='não',FECHAR_CHAMADO='não',ENCERRAR_CHAMADO='não',NOTA_CHAMADO='sim',VISUALIZAR_RELATORIO_CHAMADO='não',VISUALIZAR_COMUNICACAO='não',CADASTRAR_COMUNICACAO='não',EDITAR_COMUNICACAO='não',EXCLUIR_COMUNICACAO='não',VISUALIZAR_DOCUMENTO='sim',VISUALIZAR_TODOS_SETOR_DOCUMENTO='sim',VISUALIZAR_TODOS_ORGAO_DOCUMENTO='sim',CADASTRAR_DOCUMENTO='sim',EDITAR_DOCUMENTO='sim',EXCLUIR_DOCUMENTO='não',APROVAR_DOCUMENTO='sim',SUGESTAO_DOCUMENTO='sim',RESOLVER_DOCUMENTO='sim',VISUALIZAR_FINANCEIRO='não',CADASTRAR_RECEITA='não',EXCLUIR_RECEITA='não',CADASTRAR_DESPESA='não',EXCLUIR_DESPESA='não',AUTORIZAR_EMPENHO='não',EMPENHAR_DESPESA='não',AUTORIZAR_PAGAMENTO='não',PAGAR_DESPESA='não',VISUALIZAR_INDICE_PRODUTIVIDADE='sim',VISUALIZAR_TODOS_SETOR_INDICE_PRODUTIVIDADE='sim',VISUALIZAR_TODOS_ORGAO_INDICE_PRODUTIVIDADE='não',AVALIAR_ASSIDUIDADE='sim',NOTA_EXTRA_INDICE_PRODUTIVIDADE='sim',SER_AVALIADO_INDICE_PRODUTIVIDADE='não',VISUALIZAR_PROCESSO='sim',VISUALIZAR_TODOS_SETOR_PROCESSO='sim',VISUALIZAR_TODOS_ORGAO_PROCESSO='sim',VISUALIZAR_ARQUIVADOS_PROCESSO='sim',VISUALIZAR_SAIRAM_PROCESSO='sim',ABRIR_PROCESSO='não',EDITAR_PROCESSO='sim',EXCLUIR_PROCESSO='não',DESPACHO_PROCESSO='sim',PARECER_PROCESSO='sim',CONCLUIR_PROCESSO='não',FINALIZAR_PROCESSO='sim',FINALIZAR_GABINETE_PROCESSO='não',DESFAZER_FINALIZACAO_PROCESSO='sim',DESFAZER_FINALIZACAO_GABINETE_PROCESSO='não',ARQUIVAR_PROCESSO='sim',DESARQUIVAR_PROCESSO='sim',SAIDA_PROCESSO='não',VOLTAR_PROCESSO='não',DEFINIR_RESPONSAVEIS_PROCESSO='sim',SER_RESPONSAVEL_PROCESSO='sim',DESTINO_PROCESSO='sim',PRAZO_PROCESSO='sim',URGENCIA_PROCESSO='sim',ACESSO_GUIA_TRAMITACAO_PROCESSO='sim',APENSO_PROCESSO='sim',VISUALIZAR_SERVIDORES='não',CADASTRAR_SERVIDORES='não',EDITAR_SERVIDORES='não',EXCLUIR_SERVIDORES='não',VISUALIZAR_SETOR_RELATORIO='sim',VISUALIZAR_ORGAO_RELATORIO='não',VISUALIZAR_ODP='não',FAZER_OPERACOES_OUTROS_SETOR='sim',FAZER_OPERACOES_OUTROS_ORGAO='não' WHERE CD_SERVIDOR IN (SELECT CD_SERVIDOR FROM tb_servidores WHERE NM_FUNCAO='Superintendente' or NM_FUNCAO='Superintendente sem assessor');

UPDATE permissao SET EFETUAR_COMPRA='sim', VISUALIZAR_FINANCEIRO='sim',CADASTRAR_RECEITA='sim',EXCLUIR_RECEITA='sim',CADASTRAR_DESPESA='sim',EXCLUIR_DESPESA='sim',AUTORIZAR_EMPENHO='não',EMPENHAR_DESPESA='sim',AUTORIZAR_PAGAMENTO='não',PAGAR_DESPESA='sim' WHERE CD_SERVIDOR IN (SELECT CD_SERVIDOR FROM tb_servidores WHERE CD_SETOR='FIN');

UPDATE permissao SET VISUALIZAR_ATIVIDADE='não',VISUALIZAR_TODAS_ATIVIDADE='não',CADASTRAR_ATIVIDADE='não',AUTORIZAR_COMPRA='não',EFETUAR_COMPRA='não',VISUALIZAR_CHAMADO='sim',VISUALIZAR_TODOS_CHAMADO='não',ABRIR_CHAMADO='sim',ABRIR_TODOS_CHAMADO='não',EXCLUIR_CHAMADO='não',FECHAR_CHAMADO='não',ENCERRAR_CHAMADO='não',NOTA_CHAMADO='sim',VISUALIZAR_RELATORIO_CHAMADO='não',VISUALIZAR_COMUNICACAO='não',CADASTRAR_COMUNICACAO='não',EDITAR_COMUNICACAO='não',EXCLUIR_COMUNICACAO='não',VISUALIZAR_DOCUMENTO='sim',VISUALIZAR_TODOS_SETOR_DOCUMENTO='sim',VISUALIZAR_TODOS_ORGAO_DOCUMENTO='sim',CADASTRAR_DOCUMENTO='sim',EDITAR_DOCUMENTO='sim',EXCLUIR_DOCUMENTO='não',APROVAR_DOCUMENTO='não',SUGESTAO_DOCUMENTO='não',RESOLVER_DOCUMENTO='não',VISUALIZAR_FINANCEIRO='não',CADASTRAR_RECEITA='não',EXCLUIR_RECEITA='não',CADASTRAR_DESPESA='não',EXCLUIR_DESPESA='não',AUTORIZAR_EMPENHO='não',EMPENHAR_DESPESA='não',AUTORIZAR_PAGAMENTO='não',PAGAR_DESPESA='não',VISUALIZAR_INDICE_PRODUTIVIDADE='não',VISUALIZAR_TODOS_SETOR_INDICE_PRODUTIVIDADE='não',VISUALIZAR_TODOS_ORGAO_INDICE_PRODUTIVIDADE='não',AVALIAR_ASSIDUIDADE='não',NOTA_EXTRA_INDICE_PRODUTIVIDADE='não',SER_AVALIADO_INDICE_PRODUTIVIDADE='não',VISUALIZAR_PROCESSO='sim',VISUALIZAR_TODOS_SETOR_PROCESSO='sim',VISUALIZAR_TODOS_ORGAO_PROCESSO='sim',VISUALIZAR_ARQUIVADOS_PROCESSO='sim',VISUALIZAR_SAIRAM_PROCESSO='sim',ABRIR_PROCESSO='não',EDITAR_PROCESSO='não',EXCLUIR_PROCESSO='não',DESPACHO_PROCESSO='não',PARECER_PROCESSO='sim',CONCLUIR_PROCESSO='não',FINALIZAR_PROCESSO='não',FINALIZAR_GABINETE_PROCESSO='não',DESFAZER_FINALIZACAO_PROCESSO='não',DESFAZER_FINALIZACAO_GABINETE_PROCESSO='não',ARQUIVAR_PROCESSO='não',DESARQUIVAR_PROCESSO='não',SAIDA_PROCESSO='não',VOLTAR_PROCESSO='não',DEFINIR_RESPONSAVEIS_PROCESSO='sim',SER_RESPONSAVEL_PROCESSO='sim',DESTINO_PROCESSO='sim',PRAZO_PROCESSO='não',URGENCIA_PROCESSO='não',ACESSO_GUIA_TRAMITACAO_PROCESSO='não',APENSO_PROCESSO='sim',VISUALIZAR_SERVIDORES='não',CADASTRAR_SERVIDORES='não',EDITAR_SERVIDORES='não',EXCLUIR_SERVIDORES='não',VISUALIZAR_SETOR_RELATORIO='não',VISUALIZAR_ORGAO_RELATORIO='não',VISUALIZAR_ODP='não',FAZER_OPERACOES_OUTROS_SETOR='não',FAZER_OPERACOES_OUTROS_ORGAO='não' WHERE CD_SERVIDOR IN (SELECT CD_SERVIDOR FROM tb_servidores WHERE NM_FUNCAO='Analisa Processo');

ALTER TABLE `permissao`
  DROP `VISUALIZAR_INDICE_PRODUTIVIDADE`,
  DROP `VISUALIZAR_TODOS_SETOR_INDICE_PRODUTIVIDADE`,
  DROP `VISUALIZAR_TODOS_ORGAO_INDICE_PRODUTIVIDADE`,
  DROP `AVALIAR_ASSIDUIDADE`,
  DROP `NOTA_EXTRA_INDICE_PRODUTIVIDADE`,
  DROP `SER_AVALIADO_INDICE_PRODUTIVIDADE`,
  DROP `CONCLUIR_PROCESSO`,
  DROP `VISUALIZAR_ODP`;


#Marcando os processos como recebidos
UPDATE `tb_tramitacao_processos` SET RECEBIDO = 1;

#adicionando dados de confirmação de tramitação
ALTER TABLE `tb_tramitacao_processos` ADD `DT_CONFIRMACAO` DATE NULL AFTER `RECEBIDO`;

ALTER TABLE `tb_tramitacao_processos` CHANGE `RECEBIDO` `RECEBIDO` TINYINT(4) NOT NULL DEFAULT '0';

ALTER TABLE `tb_tramitacao_processos` CHANGE `DT_CONFIRMACAO` `DT_CONFIRMACAO` DATETIME NULL DEFAULT NULL;

ALTER TABLE `tb_tramitacao_processos` ADD `CD_SERVIDOR_CONFIRMOU` VARCHAR(17) NULL AFTER `DT_CONFIRMACAO`;


#Atualizando textos dos documentos
ALTER TABLE `tb_documentos` CHANGE `TX_DOCUMENTO` `TX_DOCUMENTO` TEXT CHARACTER SET utf8 COLLATE utf8_general_ci NULL;
UPDATE `tb_documentos` SET TX_DOCUMENTO = NULL where TX_DOCUMENTO LIKE '%sem texto%';

CREATE TABLE `tb_acompanhamento_processo` (
  `ID` int(6) NOT NULL,
  `CD_PROCESSO` varchar(20) NOT NULL,
  `CD_SETOR_RESPONSAVEL` varchar(20) DEFAULT NULL,
  `CD_SUPERINTENDENTE_RESPONSAVEL` varchar(20) DEFAULT NULL,
  `CD_SERVIDOR_RESPONSAVEL` varchar(14) DEFAULT NULL,
  `VLR_PROCESSO` double DEFAULT NULL,
  `DT_ENTRADA` datetime DEFAULT NULL,
  `DT_SAIDA` datetime DEFAULT NULL,
  `DT_DISTRIBUICAO_TECNICO` datetime DEFAULT NULL,
  `DT_DEVOLUCAO_TECNICO` datetime DEFAULT NULL,
  `NR_DIAS_TECNICO` int(11) NOT NULL DEFAULT '0',
  `DT_DISTRIBUICAO_SUPERINTENDENTE` datetime DEFAULT NULL,
  `DT_DEVOLUCAO_SUPERINTENDENTE` datetime DEFAULT NULL,
  `NR_DIAS_SUPERINTENDENTE` int(11) NOT NULL DEFAULT '0'
);

ALTER TABLE `tb_acompanhamento_processo`
  ADD PRIMARY KEY (`ID`);


ALTER TABLE `tb_acompanhamento_processo`
  MODIFY `ID` int(6) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=1;
  
 UPDATE tb_processos SET NM_STATUS = "Finalizado pelo gabinete" WHERE CD_SETOR_LOCALIZACAO='PRO' and NM_STATUS = "Finalizado pelo setor";

 UPDATE tb_servidores SET CD_SETOR = 'GAB' WHERE CD_SERVIDOR='082.766.354-40';
