<?php
$cpf = $_GET['pessoa'];

$retornoquery = mysqli_query($conexao_com_banco, "SELECT * FROM permissao WHERE CD_SERVIDOR='$cpf'");



while($result = mysqli_fetch_array($retornoquery)){
	
	$VISUALIZAR_CHAMADO = $result['VISUALIZAR_CHAMADO'];
	$VISUALIZAR_TODOS_CHAMADO = $result['VISUALIZAR_TODOS_CHAMADO'];
	$ABRIR_CHAMADO = $result['ABRIR_CHAMADO'];
	$ABRIR_TODOS_CHAMADO = $result['ABRIR_TODOS_CHAMADO'];
	$EDITAR_CHAMADO = $result['EDITAR_CHAMADO'];
	$EXCLUIR_CHAMADO = $result['EXCLUIR_CHAMADO'];
	$FECHAR_CHAMADO = $result['FECHAR_CHAMADO']; 
	$ENCERRAR_CHAMADO = $result['ENCERRAR_CHAMADO']; 
	$VISUALIZAR_RELATORIO_CHAMADO = $result['VISUALIZAR_RELATORIO_CHAMADO'];
	$VISUALIZAR_COMUNICACAO = $result['VISUALIZAR_COMUNICACAO'];
	$CADASTRAR_COMUNICACAO = $result['CADASTRAR_COMUNICACAO'];
	$EDITAR_COMUNICACAO = $result['EDITAR_COMUNICACAO'];
	$EXCLUIR_COMUNICACAO = $result['EXCLUIR_COMUNICACAO'];
	$VISUALIZAR_DOCUMENTO = $result['VISUALIZAR_DOCUMENTO'];
	$VISUALIZAR_TODOS_SETOR_DOCUMENTO = $result['VISUALIZAR_TODOS_SETOR_DOCUMENTO'];
	$VISUALIZAR_TODOS_ORGAO_DOCUMENTO = $result['VISUALIZAR_TODOS_ORGAO_DOCUMENTO'];
	$CADASTRAR_DOCUMENTO = $result['CADASTRAR_DOCUMENTO'];
	$EDITAR_DOCUMENTO = $result['EDITAR_DOCUMENTO'];
	$EXCLUIR_DOCUMENTO = $result['EXCLUIR_DOCUMENTO'];
	$APROVAR_DOCUMENTO = $result['APROVAR_DOCUMENTO'];
	$SUGESTAO_DOCUMENTO = $result['SUGESTAO_DOCUMENTO'];
	$RESOLVER_DOCUMENTO = $result['RESOLVER_DOCUMENTO'];
	$VISUALIZAR_INDICE_PRODUTIVIDADE = $result['VISUALIZAR_INDICE_PRODUTIVIDADE'];
	$VISUALIZAR_TODOS_SETOR_INDICE_PRODUTIVIDADE = $result['VISUALIZAR_TODOS_SETOR_INDICE_PRODUTIVIDADE'];
	$VISUALIZAR_TODOS_ORGAO_INDICE_PRODUTIVIDADE = $result['VISUALIZAR_TODOS_ORGAO_INDICE_PRODUTIVIDADE'];
	$AVALIAR_ASSIDUIDADE = $result['AVALIAR_ASSIDUIDADE'];
	$NOTA_EXTRA_INDICE_PRODUTIVIDADE = $result['NOTA_EXTRA_INDICE_PRODUTIVIDADE'];
	$SER_AVALIADO_INDICE_PRODUTIVIDADE = $result['SER_AVALIADO_INDICE_PRODUTIVIDADE'];
	$VISUALIZAR_PROCESSO = $result['VISUALIZAR_PROCESSO'];
	$VISUALIZAR_TODOS_SETOR_PROCESSO = $result['VISUALIZAR_TODOS_SETOR_PROCESSO'];
	$VISUALIZAR_TODOS_ORGAO_PROCESSO = $result['VISUALIZAR_TODOS_ORGAO_PROCESSO'];
	$VISUALIZAR_ARQUIVADOS_PROCESSO = $result['VISUALIZAR_ARQUIVADOS_PROCESSO'];
	$VISUALIZAR_SAIRAM_PROCESSO = $result['VISUALIZAR_SAIRAM_PROCESSO'];
	$ABRIR_PROCESSO = $result['ABRIR_PROCESSO'];
	$EDITAR_PROCESSO = $result['EDITAR_PROCESSO'];
	$EXCLUIR_PROCESSO = $result['EXCLUIR_PROCESSO'];
	$DESPACHO_PROCESSO = $result['DESPACHO_PROCESSO'];
	$PARECER_PROCESSO = $result['PARECER_PROCESSO'];
	$CONCLUIR_PROCESSO = $result['CONCLUIR_PROCESSO'];
	$FINALIZAR_PROCESSO = $result['FINALIZAR_PROCESSO'];
	$ARQUIVAR_PROCESSO = $result['ARQUIVAR_PROCESSO'];
	$SAIDA_PROCESSO = $result['SAIDA_PROCESSO'];
	$VOLTAR_PROCESSO = $result['VOLTAR_PROCESSO'];
	$DEFINIR_RESPONSAVEIS_PROCESSO = $result['DEFINIR_RESPONSAVEIS_PROCESSO'];
	$SER_RESPONSAVEL_PROCESSO = $result['SER_RESPONSAVEL_PROCESSO'];
	$DESTINO_PROCESSO = $result['DESTINO_PROCESSO'];
	$PRAZO_PROCESSO = $result['PRAZO_PROCESSO'];
	$PRAZO_FINAL_PROCESSO = $result['PRAZO_FINAL_PROCESSO'];
	$VISUALIZAR_SERVIDORES = $result['VISUALIZAR_SERVIDORES'];
	$EDITAR_SERVIDORES = $result['EDITAR_SERVIDORES'];
	$EXCLUIR_SERVIDORES = $result['EXCLUIR_SERVIDORES'];
	$VISUALIZAR_SETOR_RELATORIO = $result['VISUALIZAR_SETOR_RELATORIO'];
	$VISUALIZAR_ORGAO_RELATORIO = $result['VISUALIZAR_ORGAO_RELATORIO'];
	$FAZER_OPERACOES_OUTROS_SETOR = $result['FAZER_OPERACOES_OUTROS_SETOR'];
	$FAZER_OPERACOES_OUTROS_ORGAO = $result['FAZER_OPERACOES_OUTROS_ORGAO'];
	
}
?>