use pg2;

-- queries transformação do banco de dados;

-- criando uma coluna ID no começo da tabela tb_processos;
-- excluindo a chave primária da tabela tb_processos que é CD_PROCESSO;
-- definindo ID como chave primária e auto-incrementada;
ALTER TABLE tb_processos ADD ID INT(6) NOT NULL FIRST;

ALTER TABLE tb_processos DROP PRIMARY KEY;

ALTER TABLE tb_processos MODIFY COLUMN ID INTEGER AUTO_INCREMENT PRIMARY KEY;


-- fazendo o mesmo com a tabela de servidores (CD_SERVIDOR é a chave a ser modificada);
ALTER TABLE tb_servidores ADD ID INT(6) NOT NULL FIRST;

ALTER TABLE tb_servidores DROP PRIMARY KEY;

ALTER TABLE tb_servidores MODIFY COLUMN ID INTEGER AUTO_INCREMENT PRIMARY KEY;


-- fazendo o mesmo com a tabela de setores (CD_SETOR é a chave a ser modificada);
ALTER TABLE tb_setores ADD ID INT(6) NOT NULL FIRST;

ALTER TABLE tb_setores DROP PRIMARY KEY;

ALTER TABLE tb_setores MODIFY COLUMN ID INTEGER AUTO_INCREMENT PRIMARY KEY;


-- fazendo o mesmo com a tabela de tipos_receitas (CD_RECEITA é a chave a ser modificada);
ALTER TABLE tb_tipos_receitas ADD ID INT(6) NOT NULL FIRST;

ALTER TABLE tb_tipos_receitas DROP PRIMARY KEY;

ALTER TABLE tb_tipos_receitas MODIFY COLUMN ID INTEGER AUTO_INCREMENT PRIMARY KEY;


-- fazendo o mesmo com a tabela de tipos_despesas (CD_DESPESA é a chave a ser modificada)
ALTER TABLE tb_tipos_despesas ADD ID INT(6) NOT NULL FIRST;

ALTER TABLE tb_tipos_despesas DROP PRIMARY KEY;

ALTER TABLE tb_tipos_despesas MODIFY COLUMN ID INTEGER AUTO_INCREMENT PRIMARY KEY;





-- mudando a chave do processo na tabela documentos para o novo ID criado;
UPDATE tb_documentos doc SET CD_PROCESSO = (SELECT ID from tb_processos proc WHERE proc.CD_PROCESSO=doc.CD_PROCESSO);

-- fazendo o mesmo para outras tabelas que possuem o CD_PROCESSO
UPDATE tb_acompanhamento_processo doc SET CD_PROCESSO = (SELECT ID from tb_processos proc WHERE proc.CD_PROCESSO=doc.CD_PROCESSO);

UPDATE tb_historico_processos doc SET CD_PROCESSO = (SELECT ID from tb_processos proc WHERE proc.CD_PROCESSO=doc.CD_PROCESSO);

 UPDATE tb_despesas doc SET CD_PROCESSO = (SELECT ID from tb_processos proc WHERE proc.CD_PROCESSO=doc.CD_PROCESSO);

UPDATE tb_processos proc LEFT JOIN tb_processos proc2 ON proc.CD_PROCESSO_APENSADO = proc2.CD_PROCESSO SET proc.CD_PROCESSO_APENSADO = proc2.ID; 

UPDATE tb_responsaveis_processos doc SET CD_PROCESSO = (SELECT ID from tb_processos proc WHERE proc.CD_PROCESSO=doc.CD_PROCESSO);

UPDATE tb_tramitacao_processos doc SET CD_PROCESSO = (SELECT ID from tb_processos proc WHERE proc.CD_PROCESSO=doc.CD_PROCESSO);





-- mudando a chave do servidor na tabela notificacao para o novo ID criado;
UPDATE notificacao doc SET CD_SERVIDOR = (SELECT ID from tb_servidores proc WHERE proc.CD_SERVIDOR=doc.CD_SERVIDOR);

-- fazendo o mesmo para outras tabelas que possuem o CD_SERVIDOR
UPDATE permissao doc SET CD_SERVIDOR = (SELECT ID from tb_servidores proc WHERE proc.CD_SERVIDOR=doc.CD_SERVIDOR);

UPDATE tb_acompanhamento_processo doc SET CD_SUPERINTENDENTE_RESPONSAVEL = (SELECT ID from tb_servidores proc WHERE proc.CD_SERVIDOR=doc.CD_SUPERINTENDENTE_RESPONSAVEL);

UPDATE tb_acompanhamento_processo doc SET CD_SERVIDOR_RESPONSAVEL = (SELECT ID from tb_servidores proc WHERE proc.CD_SERVIDOR=doc.CD_SERVIDOR_RESPONSAVEL);

UPDATE tb_atividades doc SET CD_SERVIDOR = (SELECT ID from tb_servidores proc WHERE proc.CD_SERVIDOR=doc.CD_SERVIDOR);

UPDATE tb_chamados doc SET CD_SERVIDOR_REQUISITANTE = (SELECT ID from tb_servidores proc WHERE proc.CD_SERVIDOR=doc.CD_SERVIDOR_REQUISITANTE);

UPDATE tb_documentos doc SET CD_SERVIDOR_CRIACAO = (SELECT ID from tb_servidores proc WHERE proc.CD_SERVIDOR=doc.CD_SERVIDOR_CRIACAO);

UPDATE tb_documentos doc SET CD_SERVIDOR_LOCALIZACAO = (SELECT ID from tb_servidores proc WHERE proc.CD_SERVIDOR=doc.CD_SERVIDOR_LOCALIZACAO);

UPDATE tb_historico_chamados doc SET CD_SERVIDOR = (SELECT ID from tb_servidores proc WHERE proc.CD_SERVIDOR=doc.CD_SERVIDOR);

UPDATE tb_historico_despesas doc SET CD_SERVIDOR = (SELECT ID from tb_servidores proc WHERE proc.CD_SERVIDOR=doc.CD_SERVIDOR);

UPDATE tb_historico_documentos doc SET CD_SERVIDOR = (SELECT ID from tb_servidores proc WHERE proc.CD_SERVIDOR=doc.CD_SERVIDOR);

UPDATE tb_historico_processos doc SET CD_SERVIDOR = (SELECT ID from tb_servidores proc WHERE proc.CD_SERVIDOR=doc.CD_SERVIDOR);

UPDATE tb_processos doc SET CD_SERVIDOR_LOCALIZACAO = (SELECT ID from tb_servidores proc WHERE proc.CD_SERVIDOR=doc.CD_SERVIDOR_LOCALIZACAO);

UPDATE tb_processos doc SET CD_SERVIDOR_RESPONSAVEL_LIDER = (SELECT ID from tb_servidores proc WHERE proc.CD_SERVIDOR=doc.CD_SERVIDOR_RESPONSAVEL_LIDER);

UPDATE tb_responsaveis_processos doc SET CD_SERVIDOR = (SELECT ID from tb_servidores proc WHERE proc.CD_SERVIDOR=doc.CD_SERVIDOR);

UPDATE tb_tramitacao_processos doc SET CD_SERVIDOR_ORIGEM = (SELECT ID from tb_servidores proc WHERE proc.CD_SERVIDOR=doc.CD_SERVIDOR_ORIGEM);

UPDATE tb_tramitacao_processos doc SET CD_SERVIDOR_DESTINO = (SELECT ID from tb_servidores proc WHERE proc.CD_SERVIDOR=doc.CD_SERVIDOR_DESTINO);

UPDATE tb_tramitacao_processos doc SET CD_SERVIDOR_CONFIRMOU = (SELECT ID from tb_servidores proc WHERE proc.CD_SERVIDOR=doc.CD_SERVIDOR_CONFIRMOU);






-- mudando a chave do setor na tabela acompanhamento para o novo ID criado;
UPDATE tb_acompanhamento_processo doc SET CD_SETOR_RESPONSAVEL = (SELECT ID from tb_setores proc WHERE proc.CD_SETOR=doc.CD_SETOR_RESPONSAVEL);

-- fazendo o mesmo para outras tabelas que possuem o CD_SETOR
UPDATE tb_assuntos_processos doc SET CD_SETOR_RESPONSAVEL = (SELECT ID from tb_setores proc WHERE proc.CD_SETOR=doc.CD_SETOR_RESPONSAVEL);

UPDATE tb_documentos doc SET CD_SETOR_LOCALIZACAO = (SELECT ID from tb_setores proc WHERE proc.CD_SETOR=doc.CD_SETOR_LOCALIZACAO);

UPDATE tb_servidores doc SET CD_SETOR = (SELECT ID from tb_setores proc WHERE proc.CD_SETOR=doc.CD_SETOR);



-- mudando a chave da receita na tabela receitas para o novo ID criado;
 UPDATE tb_receitas doc SET CD_RECEITA = (SELECT ID from tb_tipos_receitas proc WHERE proc.CD_RECEITA=doc.CD_RECEITA);

-- mudando a chave da despesa na tabela despesas para o novo ID criado;
 UPDATE tb_despesas doc SET CD_DESPESA = (SELECT ID from tb_tipos_despesas proc WHERE proc.CD_DESPESA=doc.CD_DESPESA);



-- deletando algumas tabelas sem uso;
DROP TABLE tb_rmb;
DROP TABLE tb_historico_compras;
DROP TABLE tb_compras;
DROP TABLE tb_anexos;
DROP TABLE tb_bem_patrimonial;



-- mudando de CD_ para ID_ nas tabelas que usam os ID's de outras para identificação e padronizando o tamanho para 6
ALTER TABLE `notificacao` CHANGE `CD_SERVIDOR` `ID_SERVIDOR` INT(6) NOT NULL;

ALTER TABLE `permissao` CHANGE `ID` `ID` INT(6) NOT NULL AUTO_INCREMENT;

ALTER TABLE `permissao` CHANGE `CD_SERVIDOR` `ID_SERVIDOR` INT(6) NOT NULL;

ALTER TABLE `tb_acompanhamento_processo` CHANGE `CD_PROCESSO` `ID_PROCESSO` INT(6) NOT NULL;

ALTER TABLE `tb_acompanhamento_processo` CHANGE `CD_SETOR_RESPONSAVEL` `ID_SETOR_RESPONSAVEL` INT(6) NULL DEFAULT NULL;

ALTER TABLE `tb_acompanhamento_processo` CHANGE `CD_SUPERINTENDENTE_RESPONSAVEL` `ID_SUPERINTENDENTE_RESPONSAVEL` INT(6) NULL DEFAULT NULL;

ALTER TABLE `tb_acompanhamento_processo` CHANGE `CD_SERVIDOR_RESPONSAVEL` `ID_SERVIDOR_RESPONSAVEL` INT(6) NULL DEFAULT NULL;

ALTER TABLE `tb_anexos_atividade` CHANGE `ID` `ID` INT(6) NOT NULL AUTO_INCREMENT;

ALTER TABLE `tb_anexos_atividade` CHANGE `CD_ATIVIDADE` `ID_ATIVIDADE` INT(6) NOT NULL;

ALTER TABLE `tb_anexos_comunicacao` CHANGE `ID` `ID` INT(6) NOT NULL AUTO_INCREMENT;

ALTER TABLE `tb_anexos_comunicacao` CHANGE `CD_COMUNICACAO` `ID_COMUNICACAO` INT(6) NOT NULL;

ALTER TABLE `tb_anexos_despesa` CHANGE `ID` `ID` INT(6) NOT NULL AUTO_INCREMENT;

ALTER TABLE `tb_anexos_despesa` CHANGE `ID_DESPESA` `ID_DESPESA` INT(6) NOT NULL;

ALTER TABLE `tb_anexos_documento` CHANGE `ID` `ID` INT(6) NOT NULL AUTO_INCREMENT;

ALTER TABLE `tb_anexos_documento` CHANGE `CD_DOCUMENTO` `ID_DOCUMENTO` INT(6) NOT NULL;

ALTER TABLE `tb_assuntos_processos` CHANGE `CD_SETOR_RESPONSAVEL` `ID_SETOR_RESPONSAVEL` INT(6) NOT NULL;

ALTER TABLE `tb_atividades` CHANGE `CD_ATIVIDADE` `ID` INT(6) NOT NULL AUTO_INCREMENT;

ALTER TABLE `tb_chamados` CHANGE `CD_CHAMADO` `ID` INT(6) NOT NULL AUTO_INCREMENT;

ALTER TABLE `tb_chamados` CHANGE `CD_SERVIDOR_REQUISITANTE` `ID_SERVIDOR_REQUISITANTE` INT(6) NOT NULL;

ALTER TABLE `tb_comunicacao` CHANGE `CD_COMUNICACAO` `ID` INT(6) NOT NULL AUTO_INCREMENT;

ALTER TABLE `tb_despesas` CHANGE `ID_DESPESA` `ID` INT(6) NOT NULL AUTO_INCREMENT;

ALTER TABLE `tb_despesas` CHANGE `CD_DESPESA` `ID_DESPESA` INT(6) NOT NULL;

ALTER TABLE `tb_despesas` CHANGE `CD_PROCESSO` `ID_PROCESSO` INT(6) NOT NULL;

ALTER TABLE `tb_despesas` CHANGE `ID_PROCESSO` `ID_PROCESSO` INT(6) NULL DEFAULT NULL;

UPDATE tb_despesas SET ID_PROCESSO=NULL WHERE ID_PROCESSO=0;

ALTER TABLE `tb_documentos` CHANGE `CD_DOCUMENTO` `ID` INT(6) NOT NULL AUTO_INCREMENT;

ALTER TABLE `tb_documentos` CHANGE `CD_PROCESSO` `ID_PROCESSO` INT(6) NOT NULL;

ALTER TABLE `tb_documentos` CHANGE `ID_ASSUNTO` `ID_ASSUNTO` INT(6) NOT NULL;

ALTER TABLE `tb_documentos` CHANGE `CD_SERVIDOR_CRIACAO` `ID_SERVIDOR_CRIACAO` INT(6) NOT NULL, CHANGE `CD_SERVIDOR_LOCALIZACAO` `ID_SERVIDOR_LOCALIZACAO` INT(6) NOT NULL, CHANGE `CD_SETOR_LOCALIZACAO` `ID_SETOR_LOCALIZACAO` INT(6) NOT NULL;

ALTER TABLE `tb_historico_chamados` CHANGE `CD_CHAMADO` `ID_CHAMADO` INT(6) NOT NULL, CHANGE `CD_SERVIDOR` `ID_SERVIDOR` INT(6) NOT NULL;

ALTER TABLE `tb_historico_despesas` CHANGE `CD_SERVIDOR` `ID_SERVIDOR` INT(6) NOT NULL;

ALTER TABLE `tb_historico_documentos` CHANGE `CD_DOCUMENTO` `ID_DOCUMENTO` INT(6) NOT NULL, CHANGE `CD_SERVIDOR` `ID_SERVIDOR` INT(6) NOT NULL;

ALTER TABLE `tb_historico_processos` CHANGE `ID` `ID` INT(6) NOT NULL AUTO_INCREMENT;

ALTER TABLE `tb_historico_processos` CHANGE `CD_PROCESSO` `ID_PROCESSO` INT(6) NOT NULL;

ALTER TABLE `tb_historico_processos` CHANGE `CD_SERVIDOR` `ID_SERVIDOR` INT(6) NOT NULL;

ALTER TABLE `tb_processos` CHANGE `CD_PROCESSO` `ID_PROCESSO` VARCHAR(20) NOT NULL, CHANGE `CD_SETOR_LOCALIZACAO` `ID_SETOR_LOCALIZACAO` INT(6) NOT NULL, CHANGE `CD_SERVIDOR_LOCALIZACAO` `ID_SERVIDOR_LOCALIZACAO` INT(6) NOT NULL, CHANGE `CD_SERVIDOR_RESPONSAVEL_LIDER` `ID_SERVIDOR_RESPONSAVEL_LIDER` INT(6) NOT NULL, CHANGE `CD_PROCESSO_APENSADO` `ID_PROCESSO_APENSADO` INT(6) NOT NULL;

ALTER TABLE `tb_receitas` CHANGE `CD_RECEITA` `ID_RECEITA` INT(6) NOT NULL;

ALTER TABLE `tb_receitas` CHANGE `ID` `ID` INT(6) NOT NULL AUTO_INCREMENT;

ALTER TABLE `tb_responsaveis_processos` CHANGE `CD_PROCESSO` `ID_PROCESSO` VARCHAR(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL, CHANGE `CD_SERVIDOR` `ID_SERVIDOR` VARCHAR(14) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;

ALTER TABLE `tb_servidores` CHANGE `CD_SETOR` `ID_SETOR` INT(6) NOT NULL;

ALTER TABLE `tb_tramitacao_processos` CHANGE `CD_PROCESSO` `ID_PROCESSO` INT(6) NOT NULL, CHANGE `CD_SERVIDOR_ORIGEM` `ID_SERVIDOR_ORIGEM` INT(6) NOT NULL, CHANGE `CD_SERVIDOR_DESTINO` `ID_SERVIDOR_DESTINO` INT(6) NOT NULL, CHANGE `CD_SERVIDOR_CONFIRMOU` `ID_SERVIDOR_CONFIRMOU` INT(6) NULL DEFAULT NULL;

ALTER TABLE `tb_assuntos_processos` CHANGE `ID` `ID` INT(6) NOT NULL AUTO_INCREMENT;

ALTER TABLE `tb_atividades` CHANGE `CD_SERVIDOR` `ID_SERVIDOR` INT(6) NOT NULL;

ALTER TABLE `tb_historico_chamados` CHANGE `ID` `ID` INT(6) NOT NULL AUTO_INCREMENT;

ALTER TABLE `tb_historico_despesas` CHANGE `ID` `ID` INT(6) NOT NULL AUTO_INCREMENT;
 
ALTER TABLE `tb_historico_despesas` CHANGE `ID_DESPESA` `ID_DESPESA` INT(6) NOT NULL;

ALTER TABLE `tb_historico_documentos` CHANGE `ID` `ID` INT(6) NOT NULL AUTO_INCREMENT;

ALTER TABLE `tb_processos` CHANGE `ID` `ID` INT(6) NOT NULL AUTO_INCREMENT;

ALTER TABLE `tb_responsaveis_processos` CHANGE `ID` `ID` INT(6) NOT NULL AUTO_INCREMENT;

ALTER TABLE `tb_responsaveis_processos` CHANGE `ID_PROCESSO` `ID_PROCESSO` INT(6) NOT NULL;

ALTER TABLE `tb_responsaveis_processos` CHANGE `ID_SERVIDOR` `ID_SERVIDOR` INT(6) NOT NULL;

ALTER TABLE `tb_servidores` CHANGE `ID` `ID` INT(6) NOT NULL AUTO_INCREMENT;

UPDATE `tb_setores` SET `CD_SETOR_SUBORDINADO` = '7' WHERE `tb_setores`.`ID` = 9;
UPDATE `tb_setores` SET `CD_SETOR_SUBORDINADO` = '8' WHERE `tb_setores`.`ID` = 10;
UPDATE `tb_setores` SET `CD_SETOR_SUBORDINADO` = '11' WHERE `tb_setores`.`ID` = 11;

ALTER TABLE `tb_setores` CHANGE `ID_SETOR_SUBORDINADO` `ID_SETOR_SUBORDINADO` INT(6) NULL DEFAULT NULL;

UPDATE tb_setores SET ID_SETOR_SUBORDINADO=NULL WHERE ID_SETOR_SUBORDINADO=0;

ALTER TABLE `tb_tipos_despesas` CHANGE `ID` `ID` INT(6) NOT NULL AUTO_INCREMENT;

ALTER TABLE `tb_tipos_receitas` CHANGE `ID` `ID` INT(6) NOT NULL AUTO_INCREMENT;

ALTER TABLE `tb_tramitacao_processos` CHANGE `ID` `ID` INT(6) NOT NULL AUTO_INCREMENT;

-- setando o relacionamento de chaves estrangeiras no banco de dados
DELETE FROM `notificacao` WHERE ID_SERVIDOR NOT IN (SELECT ID FROM tb_servidores);

ALTER TABLE `notificacao` ADD FOREIGN KEY (`ID_SERVIDOR`) REFERENCES `tb_servidores`(`ID`) ON DELETE RESTRICT ON UPDATE RESTRICT;

DELETE FROM permissao WHERE ID_SERVIDOR NOT IN (SELECT ID FROM tb_servidores);

ALTER TABLE `permissao` ADD FOREIGN KEY (`ID_SERVIDOR`) REFERENCES `tb_servidores`(`ID`) ON DELETE RESTRICT ON UPDATE RESTRICT;

DELETE FROM tb_acompanhamento_processo WHERE ID_PROCESSO NOT IN (SELECT ID FROM tb_processos);

ALTER TABLE `tb_acompanhamento_processo` ADD FOREIGN KEY (`ID_PROCESSO`) REFERENCES `tb_processos`(`ID`) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE `tb_acompanhamento_processo` ADD FOREIGN KEY (`ID_SETOR_RESPONSAVEL`) REFERENCES `tb_setores`(`ID`) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE `tb_acompanhamento_processo` ADD FOREIGN KEY (`ID_SUPERINTENDENTE_RESPONSAVEL`) REFERENCES `tb_servidores`(`ID`) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE `tb_acompanhamento_processo` ADD FOREIGN KEY (`ID_SERVIDOR_RESPONSAVEL`) REFERENCES `tb_servidores`(`ID`) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE `tb_anexos_atividade` ADD FOREIGN KEY (`ID_ATIVIDADE`) REFERENCES `tb_atividades`(`ID`) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE `tb_anexos_comunicacao` ADD FOREIGN KEY (`ID_COMUNICACAO`) REFERENCES `tb_comunicacao`(`ID`) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE `tb_anexos_despesa` ADD FOREIGN KEY (`ID_DESPESA`) REFERENCES `tb_despesas`(`ID`) ON DELETE RESTRICT ON UPDATE RESTRICT;

DELETE FROM `tb_anexos_documento` WHERE ID_DOCUMENTO NOT IN (SELECT ID FROM tb_documentos);

ALTER TABLE `tb_anexos_documento` ADD FOREIGN KEY (`ID_DOCUMENTO`) REFERENCES `tb_documentos`(`ID`) ON DELETE RESTRICT ON UPDATE RESTRICT;

DELETE FROM `tb_assuntos_processos` WHERE ID_SETOR_RESPONSAVEL NOT IN (SELECT ID FROM tb_setores);

ALTER TABLE `tb_assuntos_processos` ADD FOREIGN KEY (`ID_SETOR_RESPONSAVEL`) REFERENCES `tb_setores`(`ID`) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE `tb_atividades` CHANGE `DT_VENCIMENTO` `DT_VENCIMENTO` DATE NOT NULL;

ALTER TABLE `tb_atividades` CHANGE `DT_CRIADO` `DT_CRIADO` DATE NOT NULL;

DELETE FROM `tb_atividades` WHERE ID_SERVIDOR NOT IN (SELECT serv.ID FROM tb_servidores serv) AND ID_SERVIDOR!=0;

ALTER TABLE `tb_atividades` ADD FOREIGN KEY (`ID_SERVIDOR`) REFERENCES `tb_servidores`(`ID`) ON DELETE RESTRICT ON UPDATE RESTRICT;

DELETE FROM `tb_chamados` WHERE ID_SERVIDOR_REQUISITANTE NOT IN (SELECT ID FROM tb_servidores);

ALTER TABLE `tb_chamados` ADD FOREIGN KEY (`ID_SERVIDOR_REQUISITANTE`) REFERENCES `tb_servidores`(`ID`) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE `tb_despesas` ADD FOREIGN KEY (`ID_DESPESA`) REFERENCES `tb_tipos_despesas`(`ID`) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE `tb_despesas` CHANGE `ID_PROCESSO` `ID_PROCESSO` INT(6) NULL DEFAULT NULL;

UPDATE tb_despesas SET ID_PROCESSO = NULL where ID_PROCESSO = 0;

ALTER TABLE `tb_despesas` ADD FOREIGN KEY (`ID_PROCESSO`) REFERENCES `tb_processos`(`ID`) ON DELETE RESTRICT ON UPDATE RESTRICT;



--TRANQUILO - OLHAR TB_DOCUMENTOS




DELETE FROM `tb_documentos` WHERE ID_PROCESSO NOT IN (SELECT ID FROM tb_processos);

ALTER TABLE `tb_documentos` ADD FOREIGN KEY (`ID_PROCESSO`) REFERENCES `tb_processos`(`ID`) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE `tb_documentos` ADD FOREIGN KEY (`ID_ASSUNTO`) REFERENCES `tb_assuntos_processos`(`ID`) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE `tb_documentos` ADD FOREIGN KEY (`ID_SERVIDOR_CRIACAO`) REFERENCES `tb_servidores`(`ID`) ON DELETE RESTRICT ON UPDATE RESTRICT; ALTER TABLE `tb_documentos` ADD FOREIGN KEY (`ID_SERVIDOR_LOCALIZACAO`) REFERENCES `tb_servidores`(`ID`) ON DELETE RESTRICT ON UPDATE RESTRICT; ALTER TABLE `tb_documentos` ADD FOREIGN KEY (`ID_SETOR_LOCALIZACAO`) REFERENCES `tb_setores`(`ID`) ON DELETE RESTRICT ON UPDATE RESTRICT;

DELETE FROM `tb_historico_chamados` WHERE ID_CHAMADO NOT IN (SELECT ID FROM tb_chamados);

ALTER TABLE `tb_historico_chamados` ADD FOREIGN KEY (`ID_CHAMADO`) REFERENCES `tb_chamados`(`ID`) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE `tb_historico_chamados` ADD FOREIGN KEY (`ID_SERVIDOR`) REFERENCES `tb_servidores`(`ID`) ON DELETE RESTRICT ON UPDATE RESTRICT;

DELETE FROM `tb_historico_despesas` WHERE ID_DESPESA NOT IN (SELECT ID FROM tb_despesas);

ALTER TABLE `tb_historico_despesas` ADD FOREIGN KEY (`ID_DESPESA`) REFERENCES `tb_despesas`(`ID`) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE `tb_historico_despesas` ADD FOREIGN KEY (`ID_SERVIDOR`) REFERENCES `tb_servidores`(`ID`) ON DELETE RESTRICT ON UPDATE RESTRICT;

DELETE FROM `tb_historico_documentos` WHERE ID_DOCUMENTO NOT IN (SELECT ID FROM tb_documentos);

ALTER TABLE `tb_historico_documentos` ADD FOREIGN KEY (`ID_DOCUMENTO`) REFERENCES `tb_documentos`(`ID`) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE `tb_historico_documentos` ADD FOREIGN KEY (`ID_SERVIDOR`) REFERENCES `tb_servidores`(`ID`) ON DELETE RESTRICT ON UPDATE RESTRICT;

DELETE FROM `tb_historico_processos` WHERE ID_PROCESSO NOT IN (SELECT ID FROM tb_processos);
DELETE FROM `tb_historico_processos` WHERE ID_SERVIDOR NOT IN (SELECT ID FROM tb_servidores);

ALTER TABLE `tb_historico_processos` ADD FOREIGN KEY (`ID_PROCESSO`) REFERENCES `tb_processos`(`ID`) ON DELETE RESTRICT ON UPDATE RESTRICT; ALTER TABLE `tb_historico_processos` ADD FOREIGN KEY (`ID_SERVIDOR`) REFERENCES `tb_servidores`(`ID`) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE `tb_processos` CHANGE `ID_PROCESSO_APENSADO` `ID_PROCESSO_APENSADO` INT(6) NULL DEFAULT NULL;

UPDATE tb_processos SET ID_PROCESSO_APENSADO=NULL where ID_PROCESSO_APENSADO=0;

ALTER TABLE `tb_processos` ADD FOREIGN KEY (`ID_SETOR_LOCALIZACAO`) REFERENCES `tb_setores`(`ID`) ON DELETE RESTRICT ON UPDATE RESTRICT;


ALTER TABLE `tb_processos` CHANGE `ID_ASSUNTO` `ID_ASSUNTO` INT(3) NULL DEFAULT NULL, CHANGE `ID_ORGAO_INTERESSADO` `ID_ORGAO_INTERESSADO` INT(6) NULL DEFAULT NULL, CHANGE `ID_SETOR_LOCALIZACAO` `ID_SETOR_LOCALIZACAO` INT(6) NULL DEFAULT NULL, CHANGE `ID_SERVIDOR_LOCALIZACAO` `ID_SERVIDOR_LOCALIZACAO` INT(6) NULL DEFAULT NULL, CHANGE `ID_SERVIDOR_RESPONSAVEL_LIDER` `ID_SERVIDOR_RESPONSAVEL_LIDER` INT(6) NULL DEFAULT NULL;


UPDATE tb_processos SET ID_ASSUNTO=NULL WHERE ID_ASSUNTO=0;
UPDATE tb_processos SET ID_ORGAO_INTERESSADO=NULL WHERE ID_ORGAO_INTERESSADO=0;
UPDATE tb_processos SET ID_SETOR_LOCALIZACAO=NULL WHERE ID_SETOR_LOCALIZACAO=0;
UPDATE tb_processos SET ID_SERVIDOR_LOCALIZACAO=NULL WHERE ID_SERVIDOR_LOCALIZACAO=0;
UPDATE tb_processos SET ID_SERVIDOR_RESPONSAVEL_LIDER=NULL WHERE ID_SERVIDOR_RESPONSAVEL_LIDER=0;

UPDATE tb_processos SET ID_ASSUNTO = NULL WHERE ID_ASSUNTO NOT IN (SELECT ID FROM tb_assuntos_processos);

ALTER TABLE `tb_processos` ADD FOREIGN KEY (`ID_SETOR_LOCALIZACAO`) REFERENCES `tb_setores`(`ID`) ON DELETE RESTRICT ON UPDATE RESTRICT; ALTER TABLE `tb_processos` ADD FOREIGN KEY (`ID_ORGAO_INTERESSADO`) REFERENCES `tb_orgaos`(`ID`) ON DELETE RESTRICT ON UPDATE RESTRICT; ALTER TABLE `tb_processos` ADD FOREIGN KEY (`ID_ASSUNTO`) REFERENCES `tb_assuntos_processos`(`ID`) ON DELETE RESTRICT ON UPDATE RESTRICT; ALTER TABLE `tb_processos` ADD FOREIGN KEY (`ID_SERVIDOR_LOCALIZACAO`) REFERENCES `tb_servidores`(`ID`) ON DELETE RESTRICT ON UPDATE RESTRICT; ALTER TABLE `tb_processos` ADD FOREIGN KEY (`ID_SERVIDOR_RESPONSAVEL_LIDER`) REFERENCES `tb_servidores`(`ID`) ON DELETE RESTRICT ON UPDATE RESTRICT;

DELETE FROM `tb_responsaveis_processos` WHERE ID_SERVIDOR='';

DELETE FROM `tb_responsaveis_processos` WHERE ID_PROCESSO NOT IN (SELECT ID FROM tb_processos);

ALTER TABLE `tb_responsaveis_processos` ADD FOREIGN KEY (`ID_PROCESSO`) REFERENCES `tb_processos`(`ID`) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE `tb_responsaveis_processos` ADD FOREIGN KEY (`ID_SERVIDOR`) REFERENCES `tb_servidores`(`ID`) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE `tb_servidores` ADD FOREIGN KEY (`ID_SETOR`) REFERENCES `tb_setores`(`ID`) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE `tb_setores` CHANGE `CD_SETOR_SUBORDINADO` `ID_SETOR_SUBORDINADO` INT(6) NULL DEFAULT NULL;

UPDATE tb_setores SET ID_SETOR_SUBORDINADO=NULL WHERE ID_SETOR_SUBORDINADO=0;

ALTER TABLE `tb_setores` ADD FOREIGN KEY (`ID_SETOR_SUBORDINADO`) REFERENCES `tb_setores`(`ID`) ON DELETE RESTRICT ON UPDATE RESTRICT;

DELETE FROM tb_tramitacao_processos WHERE ID_PROCESSO NOT IN (SELECT ID FROM tb_processos);

ALTER TABLE `tb_tramitacao_processos` ADD FOREIGN KEY (`ID_PROCESSO`) REFERENCES `tb_processos`(`ID`) ON DELETE RESTRICT ON UPDATE RESTRICT;

DELETE FROM tb_tramitacao_processos WHERE ID_SERVIDOR_ORIGEM NOT IN (SELECT ID FROM tb_servidores);

ALTER TABLE `tb_tramitacao_processos` ADD FOREIGN KEY (`ID_SERVIDOR_ORIGEM`) REFERENCES `tb_servidores`(`ID`) ON DELETE RESTRICT ON UPDATE RESTRICT;

DELETE FROM tb_tramitacao_processos WHERE ID_SERVIDOR_DESTINO NOT IN (SELECT ID FROM tb_servidores);

ALTER TABLE `tb_tramitacao_processos` ADD FOREIGN KEY (`ID_SERVIDOR_DESTINO`) REFERENCES `tb_servidores`(`ID`) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE `tb_tramitacao_processos` ADD FOREIGN KEY (`ID_SERVIDOR_CONFIRMOU`) REFERENCES `tb_servidores`(`ID`) ON DELETE RESTRICT ON UPDATE RESTRICT;

--organizando a tabela de servidores
ALTER TABLE `tb_servidores`
  DROP `NM_NIVEL`,
  DROP `NM_GRUPO`,
  DROP `VLR_SALARIO`,
  DROP `DT_NOMEACAO`,
  DROP `NM_SITUACAO_FUNCIONAL`,
  DROP `NM_EMAIL`,
  DROP `NM_MATRICULA`,
  DROP `NM_CEDIDO`,
  DROP `NM_GRADUACAO`;
  
  
  --TRANQUILO
  
  
  
ALTER TABLE `tb_servidores` CHANGE `NM_FUNCAO` `NM_FUNCAO` VARCHAR(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL;

UPDATE tb_servidores SET `NM_FUNCAO`= NULL WHERE `NM_FUNCAO`='';

-- alterando as permissões para 0 ou 1 ao inves de sim ou não;

ALTER TABLE `permissao` CHANGE `URGENCIA_PROCESSO` `URGENCIA_PROCESSO` VARCHAR(4) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL, CHANGE `ACESSO_GUIA_TRAMITACAO_PROCESSO` `ACESSO_GUIA_TRAMITACAO_PROCESSO` VARCHAR(3) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL;

ALTER TABLE `permissao` CHANGE `URGENCIA_PROCESSO` `URGENCIA_PROCESSO` VARCHAR(3) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL;

UPDATE permissao SET VISUALIZAR_ATIVIDADE='0' WHERE VISUALIZAR_ATIVIDADE='não';

UPDATE permissao SET VISUALIZAR_TODAS_ATIVIDADE='0' WHERE VISUALIZAR_TODAS_ATIVIDADE='não';

UPDATE permissao SET CADASTRAR_ATIVIDADE='0' WHERE CADASTRAR_ATIVIDADE='não';

UPDATE permissao SET AUTORIZAR_COMPRA='0' WHERE AUTORIZAR_COMPRA='não';

UPDATE permissao SET EFETUAR_COMPRA='0' WHERE EFETUAR_COMPRA='não';

UPDATE permissao SET VISUALIZAR_CHAMADO='0' WHERE VISUALIZAR_CHAMADO='não';

UPDATE permissao SET VISUALIZAR_TODOS_CHAMADO='0' WHERE VISUALIZAR_TODOS_CHAMADO='não';

UPDATE permissao SET ABRIR_CHAMADO='0' WHERE ABRIR_CHAMADO='não';

UPDATE permissao SET ABRIR_TODOS_CHAMADO='0' WHERE ABRIR_TODOS_CHAMADO='não';

UPDATE permissao SET EXCLUIR_CHAMADO='0' WHERE EXCLUIR_CHAMADO='não';

UPDATE permissao SET FECHAR_CHAMADO='0' WHERE FECHAR_CHAMADO='não';

UPDATE permissao SET ENCERRAR_CHAMADO='0' WHERE ENCERRAR_CHAMADO='não';

UPDATE permissao SET NOTA_CHAMADO='0' WHERE NOTA_CHAMADO='não';

UPDATE permissao SET VISUALIZAR_RELATORIO_CHAMADO='0' WHERE VISUALIZAR_RELATORIO_CHAMADO='não';

UPDATE permissao SET VISUALIZAR_COMUNICACAO='0' WHERE VISUALIZAR_COMUNICACAO='não';

UPDATE permissao SET CADASTRAR_COMUNICACAO='0' WHERE CADASTRAR_COMUNICACAO='não';

UPDATE permissao SET EDITAR_COMUNICACAO='0' WHERE EDITAR_COMUNICACAO='não';

UPDATE permissao SET EXCLUIR_COMUNICACAO='0' WHERE EXCLUIR_COMUNICACAO='não';

UPDATE permissao SET VISUALIZAR_DOCUMENTO='0' WHERE VISUALIZAR_DOCUMENTO='não';

UPDATE permissao SET VISUALIZAR_TODOS_SETOR_DOCUMENTO='0' WHERE VISUALIZAR_TODOS_SETOR_DOCUMENTO='não';

UPDATE permissao SET VISUALIZAR_TODOS_ORGAO_DOCUMENTO='0' WHERE VISUALIZAR_TODOS_ORGAO_DOCUMENTO='não';

UPDATE permissao SET CADASTRAR_DOCUMENTO='0' WHERE CADASTRAR_DOCUMENTO='não';

UPDATE permissao SET EDITAR_DOCUMENTO='0' WHERE EDITAR_DOCUMENTO='não';

UPDATE permissao SET EXCLUIR_DOCUMENTO='0' WHERE EXCLUIR_DOCUMENTO='não';

UPDATE permissao SET APROVAR_DOCUMENTO='0' WHERE APROVAR_DOCUMENTO='não';

UPDATE permissao SET SUGESTAO_DOCUMENTO='0' WHERE SUGESTAO_DOCUMENTO='não';

UPDATE permissao SET RESOLVER_DOCUMENTO='0' WHERE RESOLVER_DOCUMENTO='não';

UPDATE permissao SET VISUALIZAR_FINANCEIRO='0' WHERE VISUALIZAR_FINANCEIRO='não';

UPDATE permissao SET CADASTRAR_RECEITA='0' WHERE CADASTRAR_RECEITA='não';

UPDATE permissao SET EXCLUIR_RECEITA='0' WHERE EXCLUIR_RECEITA='não';

UPDATE permissao SET CADASTRAR_DESPESA='0' WHERE CADASTRAR_DESPESA='não';

UPDATE permissao SET EXCLUIR_DESPESA='0' WHERE EXCLUIR_DESPESA='não';

UPDATE permissao SET AUTORIZAR_EMPENHO='0' WHERE AUTORIZAR_EMPENHO='não';

UPDATE permissao SET EMPENHAR_DESPESA='0' WHERE EMPENHAR_DESPESA='não';

UPDATE permissao SET AUTORIZAR_PAGAMENTO='0' WHERE AUTORIZAR_PAGAMENTO='não';

UPDATE permissao SET PAGAR_DESPESA='0' WHERE PAGAR_DESPESA='não';

UPDATE permissao SET VISUALIZAR_PROCESSO='0' WHERE VISUALIZAR_PROCESSO='não';

UPDATE permissao SET VISUALIZAR_TODOS_SETOR_PROCESSO='0' WHERE VISUALIZAR_TODOS_SETOR_PROCESSO='não';

UPDATE permissao SET VISUALIZAR_TODOS_ORGAO_PROCESSO='0' WHERE VISUALIZAR_TODOS_ORGAO_PROCESSO='não';

UPDATE permissao SET VISUALIZAR_ARQUIVADOS_PROCESSO='0' WHERE VISUALIZAR_ARQUIVADOS_PROCESSO='não';

UPDATE permissao SET VISUALIZAR_SAIRAM_PROCESSO='0' WHERE VISUALIZAR_SAIRAM_PROCESSO='não';

UPDATE permissao SET ABRIR_PROCESSO='0' WHERE ABRIR_PROCESSO='não'; 

UPDATE permissao SET EDITAR_PROCESSO='0' WHERE EDITAR_PROCESSO='não';

UPDATE permissao SET EXCLUIR_PROCESSO='0' WHERE EXCLUIR_PROCESSO='não';

UPDATE permissao SET DESPACHO_PROCESSO='0' WHERE DESPACHO_PROCESSO='não'; 

UPDATE permissao SET PARECER_PROCESSO='0' WHERE PARECER_PROCESSO='não';
 
UPDATE permissao SET FINALIZAR_PROCESSO='0' WHERE FINALIZAR_PROCESSO='não';

UPDATE permissao SET FINALIZAR_GABINETE_PROCESSO='0' WHERE FINALIZAR_GABINETE_PROCESSO='não';

UPDATE permissao SET DESFAZER_FINALIZACAO_PROCESSO='0' WHERE DESFAZER_FINALIZACAO_PROCESSO='não';

UPDATE permissao SET DESFAZER_FINALIZACAO_GABINETE_PROCESSO='0' WHERE DESFAZER_FINALIZACAO_GABINETE_PROCESSO='não';

UPDATE permissao SET ARQUIVAR_PROCESSO='0' WHERE ARQUIVAR_PROCESSO='não';

UPDATE permissao SET DESARQUIVAR_PROCESSO='0' WHERE DESARQUIVAR_PROCESSO='não';

UPDATE permissao SET SAIDA_PROCESSO='0' WHERE SAIDA_PROCESSO='não';

UPDATE permissao SET VOLTAR_PROCESSO='0' WHERE VOLTAR_PROCESSO='não';

UPDATE permissao SET DEFINIR_RESPONSAVEIS_PROCESSO='0' WHERE DEFINIR_RESPONSAVEIS_PROCESSO='não';

UPDATE permissao SET SER_RESPONSAVEL_PROCESSO='0' WHERE SER_RESPONSAVEL_PROCESSO='não';

UPDATE permissao SET DESTINO_PROCESSO='0' WHERE DESTINO_PROCESSO='não';

UPDATE permissao SET PRAZO_PROCESSO='0' WHERE PRAZO_PROCESSO='não';

UPDATE permissao SET URGENCIA_PROCESSO='0' WHERE URGENCIA_PROCESSO='não';

UPDATE permissao SET ACESSO_GUIA_TRAMITACAO_PROCESSO='0' WHERE ACESSO_GUIA_TRAMITACAO_PROCESSO='não'; 

UPDATE permissao SET APENSO_PROCESSO='0' WHERE APENSO_PROCESSO='não';

UPDATE permissao SET VISUALIZAR_SERVIDORES='0' WHERE VISUALIZAR_SERVIDORES='não';

UPDATE permissao SET CADASTRAR_SERVIDORES='0' WHERE CADASTRAR_SERVIDORES='não';

UPDATE permissao SET EDITAR_SERVIDORES='0' WHERE EDITAR_SERVIDORES='não';

UPDATE permissao SET EXCLUIR_SERVIDORES='0' WHERE EXCLUIR_SERVIDORES='não';

UPDATE permissao SET VISUALIZAR_SETOR_RELATORIO='0' WHERE VISUALIZAR_SETOR_RELATORIO='não';

UPDATE permissao SET VISUALIZAR_ORGAO_RELATORIO='0' WHERE VISUALIZAR_ORGAO_RELATORIO='não';

UPDATE permissao SET FAZER_OPERACOES_OUTROS_SETOR='0' WHERE FAZER_OPERACOES_OUTROS_SETOR='não';

UPDATE permissao SET FAZER_OPERACOES_OUTROS_ORGAO='0' WHERE FAZER_OPERACOES_OUTROS_ORGAO='não';

UPDATE permissao SET VISUALIZAR_ATIVIDADE='1' WHERE VISUALIZAR_ATIVIDADE='sim';

UPDATE permissao SET VISUALIZAR_TODAS_ATIVIDADE='1' WHERE VISUALIZAR_TODAS_ATIVIDADE='sim';

UPDATE permissao SET CADASTRAR_ATIVIDADE='1' WHERE CADASTRAR_ATIVIDADE='sim';

UPDATE permissao SET AUTORIZAR_COMPRA='1' WHERE AUTORIZAR_COMPRA='sim';

UPDATE permissao SET EFETUAR_COMPRA='1' WHERE EFETUAR_COMPRA='sim';

UPDATE permissao SET VISUALIZAR_CHAMADO='1' WHERE VISUALIZAR_CHAMADO='sim';

UPDATE permissao SET VISUALIZAR_TODOS_CHAMADO='1' WHERE VISUALIZAR_TODOS_CHAMADO='sim';

UPDATE permissao SET ABRIR_CHAMADO='1' WHERE ABRIR_CHAMADO='sim';

UPDATE permissao SET ABRIR_TODOS_CHAMADO='1' WHERE ABRIR_TODOS_CHAMADO='sim';

UPDATE permissao SET EXCLUIR_CHAMADO='1' WHERE EXCLUIR_CHAMADO='sim';

UPDATE permissao SET FECHAR_CHAMADO='1' WHERE FECHAR_CHAMADO='sim';

UPDATE permissao SET ENCERRAR_CHAMADO='1' WHERE ENCERRAR_CHAMADO='sim';

UPDATE permissao SET NOTA_CHAMADO='1' WHERE NOTA_CHAMADO='sim';

UPDATE permissao SET VISUALIZAR_RELATORIO_CHAMADO='1' WHERE VISUALIZAR_RELATORIO_CHAMADO='sim';

UPDATE permissao SET VISUALIZAR_COMUNICACAO='1' WHERE VISUALIZAR_COMUNICACAO='sim';

UPDATE permissao SET CADASTRAR_COMUNICACAO='1' WHERE CADASTRAR_COMUNICACAO='sim';

UPDATE permissao SET EDITAR_COMUNICACAO='1' WHERE EDITAR_COMUNICACAO='sim';

UPDATE permissao SET EXCLUIR_COMUNICACAO='1' WHERE EXCLUIR_COMUNICACAO='sim';

UPDATE permissao SET VISUALIZAR_DOCUMENTO='1' WHERE VISUALIZAR_DOCUMENTO='sim';

UPDATE permissao SET VISUALIZAR_TODOS_SETOR_DOCUMENTO='1' WHERE VISUALIZAR_TODOS_SETOR_DOCUMENTO='sim';

UPDATE permissao SET VISUALIZAR_TODOS_ORGAO_DOCUMENTO='1' WHERE VISUALIZAR_TODOS_ORGAO_DOCUMENTO='sim';

UPDATE permissao SET CADASTRAR_DOCUMENTO='1' WHERE CADASTRAR_DOCUMENTO='sim';

UPDATE permissao SET EDITAR_DOCUMENTO='1' WHERE EDITAR_DOCUMENTO='sim';

UPDATE permissao SET EXCLUIR_DOCUMENTO='1' WHERE EXCLUIR_DOCUMENTO='sim';

UPDATE permissao SET APROVAR_DOCUMENTO='1' WHERE APROVAR_DOCUMENTO='sim';

UPDATE permissao SET SUGESTAO_DOCUMENTO='1' WHERE SUGESTAO_DOCUMENTO='sim';

UPDATE permissao SET RESOLVER_DOCUMENTO='1' WHERE RESOLVER_DOCUMENTO='sim';

UPDATE permissao SET VISUALIZAR_FINANCEIRO='1' WHERE VISUALIZAR_FINANCEIRO='sim';

UPDATE permissao SET CADASTRAR_RECEITA='1' WHERE CADASTRAR_RECEITA='sim';

UPDATE permissao SET EXCLUIR_RECEITA='1' WHERE EXCLUIR_RECEITA='sim';

UPDATE permissao SET CADASTRAR_DESPESA='1' WHERE CADASTRAR_DESPESA='sim';

UPDATE permissao SET EXCLUIR_DESPESA='1' WHERE EXCLUIR_DESPESA='sim';

UPDATE permissao SET AUTORIZAR_EMPENHO='1' WHERE AUTORIZAR_EMPENHO='sim';

UPDATE permissao SET EMPENHAR_DESPESA='1' WHERE EMPENHAR_DESPESA='sim';

UPDATE permissao SET AUTORIZAR_PAGAMENTO='1' WHERE AUTORIZAR_PAGAMENTO='sim';

UPDATE permissao SET PAGAR_DESPESA='1' WHERE PAGAR_DESPESA='sim';

UPDATE permissao SET VISUALIZAR_PROCESSO='1' WHERE VISUALIZAR_PROCESSO='sim';

UPDATE permissao SET VISUALIZAR_TODOS_SETOR_PROCESSO='1' WHERE VISUALIZAR_TODOS_SETOR_PROCESSO='sim';

UPDATE permissao SET VISUALIZAR_TODOS_ORGAO_PROCESSO='1' WHERE VISUALIZAR_TODOS_ORGAO_PROCESSO='sim';

UPDATE permissao SET VISUALIZAR_ARQUIVADOS_PROCESSO='1' WHERE VISUALIZAR_ARQUIVADOS_PROCESSO='sim';

UPDATE permissao SET VISUALIZAR_SAIRAM_PROCESSO='1' WHERE VISUALIZAR_SAIRAM_PROCESSO='sim';

UPDATE permissao SET ABRIR_PROCESSO='1' WHERE ABRIR_PROCESSO='sim'; 

UPDATE permissao SET EDITAR_PROCESSO='1' WHERE EDITAR_PROCESSO='sim';

UPDATE permissao SET EXCLUIR_PROCESSO='1' WHERE EXCLUIR_PROCESSO='sim';

UPDATE permissao SET DESPACHO_PROCESSO='1' WHERE DESPACHO_PROCESSO='sim'; 

UPDATE permissao SET PARECER_PROCESSO='1' WHERE PARECER_PROCESSO='sim';
 
UPDATE permissao SET FINALIZAR_PROCESSO='1' WHERE FINALIZAR_PROCESSO='sim';

UPDATE permissao SET FINALIZAR_GABINETE_PROCESSO='1' WHERE FINALIZAR_GABINETE_PROCESSO='sim';

UPDATE permissao SET DESFAZER_FINALIZACAO_PROCESSO='1' WHERE DESFAZER_FINALIZACAO_PROCESSO='sim';

UPDATE permissao SET DESFAZER_FINALIZACAO_GABINETE_PROCESSO='1' WHERE DESFAZER_FINALIZACAO_GABINETE_PROCESSO='sim';

UPDATE permissao SET ARQUIVAR_PROCESSO='1' WHERE ARQUIVAR_PROCESSO='sim';

UPDATE permissao SET DESARQUIVAR_PROCESSO='1' WHERE DESARQUIVAR_PROCESSO='sim';

UPDATE permissao SET SAIDA_PROCESSO='1' WHERE SAIDA_PROCESSO='sim';

UPDATE permissao SET VOLTAR_PROCESSO='1' WHERE VOLTAR_PROCESSO='sim';

UPDATE permissao SET DEFINIR_RESPONSAVEIS_PROCESSO='1' WHERE DEFINIR_RESPONSAVEIS_PROCESSO='sim';

UPDATE permissao SET SER_RESPONSAVEL_PROCESSO='1' WHERE SER_RESPONSAVEL_PROCESSO='sim';

UPDATE permissao SET DESTINO_PROCESSO='1' WHERE DESTINO_PROCESSO='sim';

UPDATE permissao SET PRAZO_PROCESSO='1' WHERE PRAZO_PROCESSO='sim';

UPDATE permissao SET URGENCIA_PROCESSO='1' WHERE URGENCIA_PROCESSO='sim';

UPDATE permissao SET ACESSO_GUIA_TRAMITACAO_PROCESSO='1' WHERE ACESSO_GUIA_TRAMITACAO_PROCESSO='sim'; 

UPDATE permissao SET APENSO_PROCESSO='1' WHERE APENSO_PROCESSO='sim';

UPDATE permissao SET VISUALIZAR_SERVIDORES='1' WHERE VISUALIZAR_SERVIDORES='sim';

UPDATE permissao SET CADASTRAR_SERVIDORES='1' WHERE CADASTRAR_SERVIDORES='sim';

UPDATE permissao SET EDITAR_SERVIDORES='1' WHERE EDITAR_SERVIDORES='sim';

UPDATE permissao SET EXCLUIR_SERVIDORES='1' WHERE EXCLUIR_SERVIDORES='sim';

UPDATE permissao SET VISUALIZAR_SETOR_RELATORIO='1' WHERE VISUALIZAR_SETOR_RELATORIO='sim';

UPDATE permissao SET VISUALIZAR_ORGAO_RELATORIO='1' WHERE VISUALIZAR_ORGAO_RELATORIO='sim';

UPDATE permissao SET FAZER_OPERACOES_OUTROS_SETOR='1' WHERE FAZER_OPERACOES_OUTROS_SETOR='sim';

UPDATE permissao SET FAZER_OPERACOES_OUTROS_ORGAO='1' WHERE FAZER_OPERACOES_OUTROS_ORGAO='sim';

ALTER TABLE `permissao` CHANGE VISUALIZAR_ATIVIDADE VISUALIZAR_ATIVIDADE INT(1) NOT NULL DEFAULT '0';

ALTER TABLE `permissao` CHANGE VISUALIZAR_TODAS_ATIVIDADE VISUALIZAR_TODAS_ATIVIDADE INT(1) NOT NULL DEFAULT '0';

ALTER TABLE `permissao` CHANGE CADASTRAR_ATIVIDADE CADASTRAR_ATIVIDADE INT(1) NOT NULL DEFAULT '0';

ALTER TABLE `permissao` CHANGE AUTORIZAR_COMPRA AUTORIZAR_COMPRA INT(1) NOT NULL DEFAULT '0';

ALTER TABLE `permissao` CHANGE EFETUAR_COMPRA EFETUAR_COMPRA INT(1) NOT NULL DEFAULT '0';

ALTER TABLE `permissao` CHANGE VISUALIZAR_CHAMADO VISUALIZAR_CHAMADO INT(1) NOT NULL DEFAULT '0';

ALTER TABLE `permissao` CHANGE VISUALIZAR_TODOS_CHAMADO VISUALIZAR_TODOS_CHAMADO INT(1) NOT NULL DEFAULT '0';

ALTER TABLE `permissao` CHANGE ABRIR_CHAMADO ABRIR_CHAMADO INT(1) NOT NULL DEFAULT '0';

ALTER TABLE `permissao` CHANGE ABRIR_TODOS_CHAMADO ABRIR_TODOS_CHAMADO INT(1) NOT NULL DEFAULT '0';

ALTER TABLE `permissao` CHANGE EXCLUIR_CHAMADO EXCLUIR_CHAMADO INT(1) NOT NULL DEFAULT '0';

ALTER TABLE `permissao` CHANGE FECHAR_CHAMADO FECHAR_CHAMADO INT(1) NOT NULL DEFAULT '0';

ALTER TABLE `permissao` CHANGE ENCERRAR_CHAMADO ENCERRAR_CHAMADO INT(1) NOT NULL DEFAULT '0';

ALTER TABLE `permissao` CHANGE NOTA_CHAMADO NOTA_CHAMADO INT(1) NOT NULL DEFAULT '0';

ALTER TABLE `permissao` CHANGE VISUALIZAR_RELATORIO_CHAMADO VISUALIZAR_RELATORIO_CHAMADO INT(1) NOT NULL DEFAULT '0';

ALTER TABLE `permissao` CHANGE VISUALIZAR_COMUNICACAO VISUALIZAR_COMUNICACAO INT(1) NOT NULL DEFAULT '0';

ALTER TABLE `permissao` CHANGE CADASTRAR_COMUNICACAO CADASTRAR_COMUNICACAO INT(1) NOT NULL DEFAULT '0';

ALTER TABLE `permissao` CHANGE EDITAR_COMUNICACAO EDITAR_COMUNICACAO INT(1) NOT NULL DEFAULT '0';

ALTER TABLE `permissao` CHANGE EXCLUIR_COMUNICACAO EXCLUIR_COMUNICACAO INT(1) NOT NULL DEFAULT '0';

ALTER TABLE `permissao` CHANGE VISUALIZAR_DOCUMENTO VISUALIZAR_DOCUMENTO INT(1) NOT NULL DEFAULT '0';

ALTER TABLE `permissao` CHANGE VISUALIZAR_TODOS_SETOR_DOCUMENTO VISUALIZAR_TODOS_SETOR_DOCUMENTO INT(1) NOT NULL DEFAULT '0';

ALTER TABLE `permissao` CHANGE VISUALIZAR_TODOS_ORGAO_DOCUMENTO VISUALIZAR_TODOS_ORGAO_DOCUMENTO INT(1) NOT NULL DEFAULT '0';

ALTER TABLE `permissao` CHANGE CADASTRAR_DOCUMENTO CADASTRAR_DOCUMENTO INT(1) NOT NULL DEFAULT '0';

ALTER TABLE `permissao` CHANGE EDITAR_DOCUMENTO EDITAR_DOCUMENTO INT(1) NOT NULL DEFAULT '0';

ALTER TABLE `permissao` CHANGE EXCLUIR_DOCUMENTO EXCLUIR_DOCUMENTO INT(1) NOT NULL DEFAULT '0';

ALTER TABLE `permissao` CHANGE APROVAR_DOCUMENTO APROVAR_DOCUMENTO INT(1) NOT NULL DEFAULT '0';

ALTER TABLE `permissao` CHANGE SUGESTAO_DOCUMENTO SUGESTAO_DOCUMENTO INT(1) NOT NULL DEFAULT '0';

ALTER TABLE `permissao` CHANGE RESOLVER_DOCUMENTO RESOLVER_DOCUMENTO INT(1) NOT NULL DEFAULT '0';

ALTER TABLE `permissao` CHANGE VISUALIZAR_FINANCEIRO VISUALIZAR_FINANCEIRO INT(1) NOT NULL DEFAULT '0';

ALTER TABLE `permissao` CHANGE CADASTRAR_RECEITA CADASTRAR_RECEITA INT(1) NOT NULL DEFAULT '0';

ALTER TABLE `permissao` CHANGE EXCLUIR_RECEITA EXCLUIR_RECEITA INT(1) NOT NULL DEFAULT '0';

ALTER TABLE `permissao` CHANGE CADASTRAR_DESPESA CADASTRAR_DESPESA INT(1) NOT NULL DEFAULT '0';

ALTER TABLE `permissao` CHANGE EXCLUIR_DESPESA EXCLUIR_DESPESA INT(1) NOT NULL DEFAULT '0';

ALTER TABLE `permissao` CHANGE AUTORIZAR_EMPENHO AUTORIZAR_EMPENHO INT(1) NOT NULL DEFAULT '0';

ALTER TABLE `permissao` CHANGE EMPENHAR_DESPESA EMPENHAR_DESPESA INT(1) NOT NULL DEFAULT '0';

ALTER TABLE `permissao` CHANGE AUTORIZAR_PAGAMENTO AUTORIZAR_PAGAMENTO INT(1) NOT NULL DEFAULT '0';

ALTER TABLE `permissao` CHANGE PAGAR_DESPESA PAGAR_DESPESA INT(1) NOT NULL DEFAULT '0';

ALTER TABLE `permissao` CHANGE VISUALIZAR_PROCESSO VISUALIZAR_PROCESSO INT(1) NOT NULL DEFAULT '0';

ALTER TABLE `permissao` CHANGE VISUALIZAR_TODOS_SETOR_PROCESSO VISUALIZAR_TODOS_SETOR_PROCESSO INT(1) NOT NULL DEFAULT '0';

ALTER TABLE `permissao` CHANGE VISUALIZAR_TODOS_ORGAO_PROCESSO VISUALIZAR_TODOS_ORGAO_PROCESSO INT(1) NOT NULL DEFAULT '0';

ALTER TABLE `permissao` CHANGE VISUALIZAR_ARQUIVADOS_PROCESSO VISUALIZAR_ARQUIVADOS_PROCESSO INT(1) NOT NULL DEFAULT '0';

ALTER TABLE `permissao` CHANGE VISUALIZAR_SAIRAM_PROCESSO VISUALIZAR_SAIRAM_PROCESSO INT(1) NOT NULL DEFAULT '0';

ALTER TABLE `permissao` CHANGE ABRIR_PROCESSO ABRIR_PROCESSO INT(1) NOT NULL DEFAULT '0';

ALTER TABLE `permissao` CHANGE EDITAR_PROCESSO EDITAR_PROCESSO INT(1) NOT NULL DEFAULT '0';

ALTER TABLE `permissao` CHANGE EXCLUIR_PROCESSO EXCLUIR_PROCESSO INT(1) NOT NULL DEFAULT '0';

ALTER TABLE `permissao` CHANGE DESPACHO_PROCESSO DESPACHO_PROCESSO INT(1) NOT NULL DEFAULT '0';

ALTER TABLE `permissao` CHANGE PARECER_PROCESSO PARECER_PROCESSO INT(1) NOT NULL DEFAULT '0';

ALTER TABLE `permissao` CHANGE FINALIZAR_PROCESSO FINALIZAR_PROCESSO INT(1) NOT NULL DEFAULT '0';

ALTER TABLE `permissao` CHANGE FINALIZAR_GABINETE_PROCESSO FINALIZAR_GABINETE_PROCESSO INT(1) NOT NULL DEFAULT '0';

ALTER TABLE `permissao` CHANGE DESFAZER_FINALIZACAO_PROCESSO DESFAZER_FINALIZACAO_PROCESSO INT(1) NOT NULL DEFAULT '0';

ALTER TABLE `permissao` CHANGE DESFAZER_FINALIZACAO_GABINETE_PROCESSO DESFAZER_FINALIZACAO_GABINETE_PROCESSO INT(1) NOT NULL DEFAULT '0';

ALTER TABLE `permissao` CHANGE ARQUIVAR_PROCESSO ARQUIVAR_PROCESSO INT(1) NOT NULL DEFAULT '0';

ALTER TABLE `permissao` CHANGE DESARQUIVAR_PROCESSO DESARQUIVAR_PROCESSO INT(1) NOT NULL DEFAULT '0';

ALTER TABLE `permissao` CHANGE SAIDA_PROCESSO SAIDA_PROCESSO INT(1) NOT NULL DEFAULT '0';

ALTER TABLE `permissao` CHANGE VOLTAR_PROCESSO VOLTAR_PROCESSO INT(1) NOT NULL DEFAULT '0';

ALTER TABLE `permissao` CHANGE DEFINIR_RESPONSAVEIS_PROCESSO DEFINIR_RESPONSAVEIS_PROCESSO INT(1) NOT NULL DEFAULT '0';

ALTER TABLE `permissao` CHANGE SER_RESPONSAVEL_PROCESSO SER_RESPONSAVEL_PROCESSO INT(1) NOT NULL DEFAULT '0';

ALTER TABLE `permissao` CHANGE DESTINO_PROCESSO DESTINO_PROCESSO INT(1) NOT NULL DEFAULT '0';

ALTER TABLE `permissao` CHANGE PRAZO_PROCESSO PRAZO_PROCESSO INT(1) NOT NULL DEFAULT '0';

ALTER TABLE `permissao` CHANGE URGENCIA_PROCESSO URGENCIA_PROCESSO INT(1) NOT NULL DEFAULT '0';

ALTER TABLE `permissao` CHANGE ACESSO_GUIA_TRAMITACAO_PROCESSO ACESSO_GUIA_TRAMITACAO_PROCESSO INT(1) NOT NULL DEFAULT '0';

ALTER TABLE `permissao` CHANGE APENSO_PROCESSO APENSO_PROCESSO INT(1) NOT NULL DEFAULT '0';

ALTER TABLE `permissao` CHANGE VISUALIZAR_SERVIDORES VISUALIZAR_SERVIDORES INT(1) NOT NULL DEFAULT '0';

ALTER TABLE `permissao` CHANGE CADASTRAR_SERVIDORES CADASTRAR_SERVIDORES INT(1) NOT NULL DEFAULT '0';

ALTER TABLE `permissao` CHANGE EDITAR_SERVIDORES EDITAR_SERVIDORES INT(1) NOT NULL DEFAULT '0';

ALTER TABLE `permissao` CHANGE EXCLUIR_SERVIDORES EXCLUIR_SERVIDORES INT(1) NOT NULL DEFAULT '0';

ALTER TABLE `permissao` CHANGE VISUALIZAR_SETOR_RELATORIO VISUALIZAR_SETOR_RELATORIO INT(1) NOT NULL DEFAULT '0';

ALTER TABLE `permissao` CHANGE VISUALIZAR_ORGAO_RELATORIO VISUALIZAR_ORGAO_RELATORIO INT(1) NOT NULL DEFAULT '0';

ALTER TABLE `permissao` CHANGE FAZER_OPERACOES_OUTROS_SETOR FAZER_OPERACOES_OUTROS_SETOR INT(1) NOT NULL DEFAULT '0';

ALTER TABLE `permissao` CHANGE FAZER_OPERACOES_OUTROS_ORGAO FAZER_OPERACOES_OUTROS_ORGAO INT(1) NOT NULL DEFAULT '0';

ALTER TABLE `permissao` CHANGE VISUALIZAR_ATIVIDADE VISUALIZAR_ATIVIDADE INT(1) NOT NULL DEFAULT '0';

ALTER TABLE `permissao` CHANGE VISUALIZAR_TODAS_ATIVIDADE VISUALIZAR_TODAS_ATIVIDADE INT(1) NOT NULL DEFAULT '0';

ALTER TABLE `permissao` CHANGE CADASTRAR_ATIVIDADE CADASTRAR_ATIVIDADE INT(1) NOT NULL DEFAULT '0';

ALTER TABLE `permissao` CHANGE AUTORIZAR_COMPRA AUTORIZAR_COMPRA INT(1) NOT NULL DEFAULT '0';

ALTER TABLE `permissao` CHANGE EFETUAR_COMPRA EFETUAR_COMPRA INT(1) NOT NULL DEFAULT '0';

ALTER TABLE `permissao` CHANGE VISUALIZAR_CHAMADO VISUALIZAR_CHAMADO INT(1) NOT NULL DEFAULT '0';

ALTER TABLE `permissao` CHANGE VISUALIZAR_TODOS_CHAMADO VISUALIZAR_TODOS_CHAMADO INT(1) NOT NULL DEFAULT '0';

ALTER TABLE `permissao` CHANGE ABRIR_CHAMADO ABRIR_CHAMADO INT(1) NOT NULL DEFAULT '0';

ALTER TABLE `permissao` CHANGE ABRIR_TODOS_CHAMADO ABRIR_TODOS_CHAMADO INT(1) NOT NULL DEFAULT '0';

ALTER TABLE `permissao` CHANGE EXCLUIR_CHAMADO EXCLUIR_CHAMADO INT(1) NOT NULL DEFAULT '0';

ALTER TABLE `permissao` CHANGE FECHAR_CHAMADO FECHAR_CHAMADO INT(1) NOT NULL DEFAULT '0';

ALTER TABLE `permissao` CHANGE ENCERRAR_CHAMADO ENCERRAR_CHAMADO INT(1) NOT NULL DEFAULT '0';

ALTER TABLE `permissao` CHANGE NOTA_CHAMADO NOTA_CHAMADO INT(1) NOT NULL DEFAULT '0';

ALTER TABLE `permissao` CHANGE VISUALIZAR_RELATORIO_CHAMADO VISUALIZAR_RELATORIO_CHAMADO INT(1) NOT NULL DEFAULT '0';

ALTER TABLE `permissao` CHANGE VISUALIZAR_COMUNICACAO VISUALIZAR_COMUNICACAO INT(1) NOT NULL DEFAULT '0';

ALTER TABLE `permissao` CHANGE CADASTRAR_COMUNICACAO CADASTRAR_COMUNICACAO INT(1) NOT NULL DEFAULT '0';

ALTER TABLE `permissao` CHANGE EDITAR_COMUNICACAO EDITAR_COMUNICACAO INT(1) NOT NULL DEFAULT '0';

ALTER TABLE `permissao` CHANGE EXCLUIR_COMUNICACAO EXCLUIR_COMUNICACAO INT(1) NOT NULL DEFAULT '0';

ALTER TABLE `permissao` CHANGE VISUALIZAR_DOCUMENTO VISUALIZAR_DOCUMENTO INT(1) NOT NULL DEFAULT '0';

ALTER TABLE `permissao` CHANGE VISUALIZAR_TODOS_SETOR_DOCUMENTO VISUALIZAR_TODOS_SETOR_DOCUMENTO INT(1) NOT NULL DEFAULT '0';

ALTER TABLE `permissao` CHANGE VISUALIZAR_TODOS_ORGAO_DOCUMENTO VISUALIZAR_TODOS_ORGAO_DOCUMENTO INT(1) NOT NULL DEFAULT '0';

ALTER TABLE `permissao` CHANGE CADASTRAR_DOCUMENTO CADASTRAR_DOCUMENTO INT(1) NOT NULL DEFAULT '0';

ALTER TABLE `permissao` CHANGE EDITAR_DOCUMENTO EDITAR_DOCUMENTO INT(1) NOT NULL DEFAULT '0';

ALTER TABLE `permissao` CHANGE EXCLUIR_DOCUMENTO EXCLUIR_DOCUMENTO INT(1) NOT NULL DEFAULT '0';

ALTER TABLE `permissao` CHANGE APROVAR_DOCUMENTO APROVAR_DOCUMENTO INT(1) NOT NULL DEFAULT '0';

ALTER TABLE `permissao` CHANGE SUGESTAO_DOCUMENTO SUGESTAO_DOCUMENTO INT(1) NOT NULL DEFAULT '0';

ALTER TABLE `permissao` CHANGE RESOLVER_DOCUMENTO RESOLVER_DOCUMENTO INT(1) NOT NULL DEFAULT '0';

ALTER TABLE `permissao` CHANGE VISUALIZAR_FINANCEIRO VISUALIZAR_FINANCEIRO INT(1) NOT NULL DEFAULT '0';

ALTER TABLE `permissao` CHANGE CADASTRAR_RECEITA CADASTRAR_RECEITA INT(1) NOT NULL DEFAULT '0';

ALTER TABLE `permissao` CHANGE EXCLUIR_RECEITA EXCLUIR_RECEITA INT(1) NOT NULL DEFAULT '0';

ALTER TABLE `permissao` CHANGE CADASTRAR_DESPESA CADASTRAR_DESPESA INT(1) NOT NULL DEFAULT '0';

ALTER TABLE `permissao` CHANGE EXCLUIR_DESPESA EXCLUIR_DESPESA INT(1) NOT NULL DEFAULT '0';

ALTER TABLE `permissao` CHANGE AUTORIZAR_EMPENHO AUTORIZAR_EMPENHO INT(1) NOT NULL DEFAULT '0';

ALTER TABLE `permissao` CHANGE EMPENHAR_DESPESA EMPENHAR_DESPESA INT(1) NOT NULL DEFAULT '0';

ALTER TABLE `permissao` CHANGE AUTORIZAR_PAGAMENTO AUTORIZAR_PAGAMENTO INT(1) NOT NULL DEFAULT '0';

ALTER TABLE `permissao` CHANGE PAGAR_DESPESA PAGAR_DESPESA INT(1) NOT NULL DEFAULT '0';

ALTER TABLE `permissao` CHANGE VISUALIZAR_PROCESSO VISUALIZAR_PROCESSO INT(1) NOT NULL DEFAULT '0';

ALTER TABLE `permissao` CHANGE VISUALIZAR_TODOS_SETOR_PROCESSO VISUALIZAR_TODOS_SETOR_PROCESSO INT(1) NOT NULL DEFAULT '0';

ALTER TABLE `permissao` CHANGE VISUALIZAR_TODOS_ORGAO_PROCESSO VISUALIZAR_TODOS_ORGAO_PROCESSO INT(1) NOT NULL DEFAULT '0';

ALTER TABLE `permissao` CHANGE VISUALIZAR_ARQUIVADOS_PROCESSO VISUALIZAR_ARQUIVADOS_PROCESSO INT(1) NOT NULL DEFAULT '0';

ALTER TABLE `permissao` CHANGE VISUALIZAR_SAIRAM_PROCESSO VISUALIZAR_SAIRAM_PROCESSO INT(1) NOT NULL DEFAULT '0';

ALTER TABLE `permissao` CHANGE ABRIR_PROCESSO ABRIR_PROCESSO INT(1) NOT NULL DEFAULT '0';

ALTER TABLE `permissao` CHANGE EDITAR_PROCESSO EDITAR_PROCESSO INT(1) NOT NULL DEFAULT '0';

ALTER TABLE `permissao` CHANGE EXCLUIR_PROCESSO EXCLUIR_PROCESSO INT(1) NOT NULL DEFAULT '0';

ALTER TABLE `permissao` CHANGE DESPACHO_PROCESSO DESPACHO_PROCESSO INT(1) NOT NULL DEFAULT '0';

ALTER TABLE `permissao` CHANGE PARECER_PROCESSO PARECER_PROCESSO INT(1) NOT NULL DEFAULT '0';

ALTER TABLE `permissao` CHANGE FINALIZAR_PROCESSO FINALIZAR_PROCESSO INT(1) NOT NULL DEFAULT '0';

ALTER TABLE `permissao` CHANGE FINALIZAR_GABINETE_PROCESSO FINALIZAR_GABINETE_PROCESSO INT(1) NOT NULL DEFAULT '0';

ALTER TABLE `permissao` CHANGE DESFAZER_FINALIZACAO_PROCESSO DESFAZER_FINALIZACAO_PROCESSO INT(1) NOT NULL DEFAULT '0';

ALTER TABLE `permissao` CHANGE DESFAZER_FINALIZACAO_GABINETE_PROCESSO DESFAZER_FINALIZACAO_GABINETE_PROCESSO INT(1) NOT NULL DEFAULT '0';

ALTER TABLE `permissao` CHANGE ARQUIVAR_PROCESSO ARQUIVAR_PROCESSO INT(1) NOT NULL DEFAULT '0';

ALTER TABLE `permissao` CHANGE DESARQUIVAR_PROCESSO DESARQUIVAR_PROCESSO INT(1) NOT NULL DEFAULT '0';

ALTER TABLE `permissao` CHANGE SAIDA_PROCESSO SAIDA_PROCESSO INT(1) NOT NULL DEFAULT '0';

ALTER TABLE `permissao` CHANGE VOLTAR_PROCESSO VOLTAR_PROCESSO INT(1) NOT NULL DEFAULT '0';

ALTER TABLE `permissao` CHANGE DEFINIR_RESPONSAVEIS_PROCESSO DEFINIR_RESPONSAVEIS_PROCESSO INT(1) NOT NULL DEFAULT '0';

ALTER TABLE `permissao` CHANGE SER_RESPONSAVEL_PROCESSO SER_RESPONSAVEL_PROCESSO INT(1) NOT NULL DEFAULT '0';

ALTER TABLE `permissao` CHANGE DESTINO_PROCESSO DESTINO_PROCESSO INT(1) NOT NULL DEFAULT '0';

ALTER TABLE `permissao` CHANGE PRAZO_PROCESSO PRAZO_PROCESSO INT(1) NOT NULL DEFAULT '0';

ALTER TABLE `permissao` CHANGE URGENCIA_PROCESSO URGENCIA_PROCESSO INT(1) NOT NULL DEFAULT '0';

ALTER TABLE `permissao` CHANGE ACESSO_GUIA_TRAMITACAO_PROCESSO ACESSO_GUIA_TRAMITACAO_PROCESSO INT(1) NOT NULL DEFAULT '0';

ALTER TABLE `permissao` CHANGE APENSO_PROCESSO APENSO_PROCESSO INT(1) NOT NULL DEFAULT '0';

ALTER TABLE `permissao` CHANGE VISUALIZAR_SERVIDORES VISUALIZAR_SERVIDORES INT(1) NOT NULL DEFAULT '0';

ALTER TABLE `permissao` CHANGE CADASTRAR_SERVIDORES CADASTRAR_SERVIDORES INT(1) NOT NULL DEFAULT '0';

ALTER TABLE `permissao` CHANGE EDITAR_SERVIDORES EDITAR_SERVIDORES INT(1) NOT NULL DEFAULT '0';

ALTER TABLE `permissao` CHANGE EXCLUIR_SERVIDORES EXCLUIR_SERVIDORES INT(1) NOT NULL DEFAULT '0';

ALTER TABLE `permissao` CHANGE VISUALIZAR_SETOR_RELATORIO VISUALIZAR_SETOR_RELATORIO INT(1) NOT NULL DEFAULT '0';

ALTER TABLE `permissao` CHANGE VISUALIZAR_ORGAO_RELATORIO VISUALIZAR_ORGAO_RELATORIO INT(1) NOT NULL DEFAULT '0';

ALTER TABLE `permissao` CHANGE FAZER_OPERACOES_OUTROS_SETOR FAZER_OPERACOES_OUTROS_SETOR INT(1) NOT NULL DEFAULT '0';

ALTER TABLE `permissao` CHANGE FAZER_OPERACOES_OUTROS_ORGAO FAZER_OPERACOES_OUTROS_ORGAO INT(1) NOT NULL DEFAULT '0';

-- colocar nomes de status com letras maiusculas

UPDATE tb_chamados SET NM_NATUREZA = UPPER(NM_NATUREZA);

UPDATE tb_chamados SET NM_STATUS = UPPER(NM_STATUS);

UPDATE tb_chamados SET NM_NOTA = UPPER(NM_NOTA);

UPDATE tb_comunicacao SET NM_STATUS = UPPER(NM_STATUS);

UPDATE tb_despesas SET NM_STATUS = UPPER(NM_STATUS);

UPDATE tb_documentos SET NM_STATUS = UPPER(NM_STATUS);

UPDATE tb_historico_chamados SET NM_ACAO = UPPER(NM_ACAO);

UPDATE tb_historico_despesas SET NM_ACAO = UPPER(NM_ACAO);

UPDATE tb_historico_documentos SET NM_ACAO = UPPER(NM_ACAO);

UPDATE tb_historico_processos SET NM_ACAO = UPPER(NM_ACAO);

UPDATE tb_processos SET NM_STATUS = UPPER(NM_STATUS);

ALTER TABLE `tb_chamados` CHANGE `DT_FECHAMENTO` `DT_FECHAMENTO` DATETIME NULL DEFAULT NULL, CHANGE `DT_ENCERRAMENTO` `DT_ENCERRAMENTO` DATETIME NULL DEFAULT NULL, CHANGE `NM_NOTA` `NM_NOTA` VARCHAR(20) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL;

UPDATE tb_chamados SET DT_FECHAMENTO = NULL where DT_FECHAMENTO = '';

ALTER TABLE `tb_chamados` CHANGE `NM_NOTA` `NM_AVALIACAO` VARCHAR(20) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL;

ALTER TABLE `tb_comunicacao` CHANGE `NM_TEXTO` `TX_NOTICIA` TEXT CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL;

UPDATE tb_comunicacao SET TX_NOTICIA = NULL WHERE TX_NOTICIA = '<p>Sem texto</p>';
update tb_comunicacao SET TX_NOTICIA = NULL WHERE TX_NOTICIA = '';
update tb_comunicacao SET TX_NOTICIA = NULL WHERE TX_NOTICIA = 'Sem texto';

ALTER TABLE `tb_despesas` CHANGE `DS_DESPESA` `DS_DESPESA` VARCHAR(500) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL;

UPDATE tb_despesas SET DS_DESPESA = NULL WHERE DS_DESPESA = '';

ALTER TABLE `tb_documentos` CHANGE `DT_RESOLVIDO` `DT_RESOLVIDO` DATE NULL DEFAULT NULL, CHANGE `VLR_DOCUMENTO` `VLR_DOCUMENTO` DOUBLE NULL DEFAULT NULL;

UPDATE tb_documentos set DT_RESOLVIDO = NULL WHERE DT_RESOLVIDO = '';
UPDATE tb_documentos set VLR_DOCUMENTO = NULL WHERE VLR_DOCUMENTO = '';

ALTER TABLE `tb_processos` CHANGE `DT_SAIDA` `DT_SAIDA` DATE NULL DEFAULT NULL, CHANGE `NR_DIAS` `NR_DIAS` INT(4) NOT NULL DEFAULT '0';



ALTER TABLE `tb_receitas` CHANGE `VLR_RECEITA` `VLR_RECEITA` DOUBLE NOT NULL DEFAULT '0';

ALTER TABLE `tb_tramitacao_processos` CHANGE `RECEBIDO` `NR_RECEBIDO` INT(1) NOT NULL DEFAULT '0';

ALTER TABLE `tb_receitas` CHANGE `VLR_RECEITA` `VL_RECEITA` DOUBLE NOT NULL DEFAULT '0';

ALTER TABLE `tb_documentos` CHANGE `VLR_DOCUMENTO` `VL_DOCUMENTO` DOUBLE NULL DEFAULT NULL;

ALTER TABLE `tb_despesas` CHANGE `VLR_DESPESA` `VL_DESPESA` DOUBLE NOT NULL;

ALTER TABLE `tb_caixa` CHANGE `VLR_CAIXA` `VL_CAIXA` DOUBLE NOT NULL;

ALTER TABLE `tb_acompanhamento_processo` CHANGE `VLR_PROCESSO` `VL_PROCESSO` DOUBLE NULL DEFAULT NULL;

UPDATE tb_processos p SET ID_SETOR_LOCALIZACAO=(SELECT ID_SETOR FROM tb_servidores WHERE ID=p.ID_SERVIDOR_LOCALIZACAO);

ALTER TABLE `tb_processos` CHANGE `ID_PROCESSO` `CD_PROCESSO` VARCHAR(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;

ALTER TABLE `tb_processos` CHANGE `NR_URGENCIA` `BL_URGENCIA` BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE `tb_processos` CHANGE `NM_STATUS` `NM_STATUS` ENUM('EM ANDAMENTO','ATRASADO','FINALIZADO PELO SETOR','FINALIZADO PELO GABINETE','ARQUIVADO','SAIU') NOT NULL;